export type LessonGuide = {
  concept: string;
  steps: [string, string, string];
  code: string;
  output: string;
  explanation: string;
  caution: string;
};

// One reviewed teaching example per unit. These examples are deliberately
// different from the graded exercises, so the guide teaches without giving
// away the answer. The lesson's own description supplies its level's focus.
export const LESSON_GUIDES: Record<string, LessonGuide> = {
  u1: { concept: "Un programa es una lista de instrucciones que Python ejecuta de arriba hacia abajo.", steps: ["Escribe una instrucción: print muestra información en la pantalla.", "Pon el texto entre comillas para distinguirlo de un nombre de variable.", "Usa # para dejar una nota: Python no ejecuta esa línea."], code: "# Un saludo para empezar\nprint('Hola, mundo')\nprint('Vamos paso a paso')", output: "Hola, mundo\nVamos paso a paso", explanation: "Python ignora el comentario y ejecuta cada print en orden. Cada llamada crea una línea nueva.", caution: "Sin comillas, Hola sería un nombre de variable que tendrías que haber definido." },
  u2: { concept: "Una variable vincula un nombre con un valor. El tipo del valor decide qué operaciones son posibles.", steps: ["Asigna un valor con =; a la izquierda va el nombre.", "type te permite inspeccionar si el valor es int, float, str o bool.", "Convierte texto numérico con int o float antes de calcular."], code: "edad = '20'\nprint(type(edad).__name__)\nprint(int(edad) + 1)", output: "str\n21", explanation: "'20' sigue siendo texto aunque tenga dígitos. int lo convierte en número y entonces la suma produce 21.", caution: "'20' + '1' produce '201'; no realiza una suma numérica." },
  u3: { concept: "Los operadores calculan, comparan y combinan condiciones; sus reglas de precedencia importan.", steps: ["Usa +, -, *, / y % para operar con números.", "Una comparación como > produce True o False.", "Agrupa condiciones con and, or, not y paréntesis cuando la intención pueda confundirse."], code: "precio = 12\nprint(precio * 2 + 3)\nprint(precio % 5)\nprint(precio > 10 and precio < 20)", output: "27\n2\nTrue", explanation: "Primero se multiplica, % devuelve el resto de 12 dividido entre 5 y and exige que ambas comparaciones sean verdaderas.", caution: "Para comparar usa ==; = asigna un valor." },
  u4: { concept: "Un string es una secuencia de caracteres que puedes consultar y transformar sin modificar el original.", steps: ["Los índices empiezan en 0; [-1] apunta al último carácter.", "Un slice [inicio:fin] incluye inicio y excluye fin.", "Los métodos devuelven otro string: guarda el resultado si lo necesitas."], code: "nombre = 'PyQuest'\nprint(nombre[0])\nprint(nombre[2:5])\nprint(nombre.lower())", output: "P\nQue\npyquest", explanation: "[2:5] toma los caracteres en las posiciones 2, 3 y 4. lower crea una versión en minúsculas.", caution: "nombre.lower() no cambia nombre por sí solo: asigna el resultado a una variable." },
  u5: { concept: "Una lista guarda elementos ordenados y se puede modificar; una copia evita compartir cambios por accidente.", steps: ["Crea una lista con corchetes y consulta elementos por posición.", "append añade un elemento y modifica la lista existente.", "copy crea otra lista; asignar solo otro nombre comparte la misma lista."], code: "notas = [7, 9]\ncopia = notas.copy()\nnotas.append(10)\nprint(notas)\nprint(copia)", output: "[7, 9, 10]\n[7, 9]", explanation: "append modificó notas. copia conserva los valores de antes porque es un objeto distinto.", caution: "si haces copia = notas, ambas variables apuntarán a la misma lista." },
  u6: { concept: "Una tupla conserva posiciones sin permitir cambios; un set elimina duplicados y sirve para pertenencia.", steps: ["Usa (a, b) para un registro cuyo orden importa.", "Usa {a, b} si importan los valores únicos.", "Comprueba pertenencia con in; no dependas del orden de un set."], code: "registro = ('Ana', 23)\netiquetas = {'IA', 'datos', 'IA'}\nprint(registro[0])\nprint(len(etiquetas))\nprint('IA' in etiquetas)", output: "Ana\n2\nTrue", explanation: "La tupla retiene 'Ana' en la primera posición; el set almacena 'IA' una sola vez.", caution: "No intentes indexar un set ni modificar una posición de la tupla." },
  u7: { concept: "Un diccionario relaciona cada clave con un valor; puedes consultar datos por su nombre.", steps: ["Escribe pares clave: valor entre llaves.", "Consulta con corchetes cuando sabes que la clave existe.", "Usa get para ofrecer un valor por defecto cuando podría faltar."], code: "persona = {'nombre': 'Lía', 'edad': 20}\nprint(persona['nombre'])\nprint(persona.get('ciudad', 'sin dato'))", output: "Lía\nsin dato", explanation: "La primera clave existe; get devuelve el valor alternativo porque 'ciudad' no está presente.", caution: "persona['ciudad'] produciría KeyError si no existe esa clave." },
  u8: { concept: "Una condición permite elegir un camino; la indentación indica qué instrucciones pertenecen a cada rama.", steps: ["if prueba la primera condición.", "elif prueba otra solo si las anteriores fallaron.", "else recoge los casos restantes; se ejecuta una sola rama."], code: "puntos = 72\nif puntos >= 90:\n    print('excelente')\nelif puntos >= 60:\n    print('aprobado')\nelse:\n    print('a practicar')", output: "aprobado", explanation: "72 no alcanza 90, pero sí 60: Python ejecuta esa rama y se salta las demás.", caution: "No olvides los dos puntos ni la indentación debajo de cada condición." },
  u9: { concept: "Un bucle repite instrucciones; for recorre valores y while continúa mientras una condición sea verdadera.", steps: ["range(3) genera 0, 1 y 2: el extremo final no entra.", "Coloca un acumulador fuera del bucle para conservar el total.", "Actualiza el acumulador dentro del bloque indentado."], code: "total = 0\nfor numero in range(1, 4):\n    total += numero\nprint(total)", output: "6", explanation: "El for suma 1, luego 2 y luego 3. El print está fuera del bucle y muestra el total final.", caution: "Si inicializas total dentro del for, borrarás el progreso en cada vuelta." },
  u10: { concept: "Una función reúne una tarea con nombre, recibe parámetros y puede entregar un resultado reutilizable.", steps: ["def crea la función y nombra sus parámetros.", "return entrega el valor al lugar desde el que la llamaste.", "Llama la función con argumentos dentro de paréntesis."], code: "def doble(numero):\n    return numero * 2\n\nresultado = doble(6)\nprint(resultado)", output: "12", explanation: "6 entra como numero, se multiplica por 2 y return entrega 12 a resultado.", caution: "print dentro de una función muestra información; return permite usar el valor después." },
  u11: { concept: "Una excepción informa qué falló; try/except permite responder a un error concreto.", steps: ["La línea dentro de try puede producir una excepción.", "except captura el tipo de error esperado.", "Decide qué valor usar si el dato no se puede convertir."], code: "dato = 'sin dato'\ntry:\n    numero = int(dato)\nexcept ValueError:\n    numero = 0\nprint(numero)", output: "0", explanation: "int no puede convertir ese texto y lanza ValueError. El programa usa 0 como alternativa.", caution: "Capturar todos los errores sin distinguirlos puede ocultar un fallo de programación." },
  u12: { concept: "Una clase define cómo se construyen objetos; cada instancia guarda su propio estado en self.", steps: ["__init__ prepara cada objeto al crearlo.", "self.atributo pertenece a esa instancia.", "Un método puede leer o cambiar ese estado."], code: "class Contador:\n    def __init__(self):\n        self.valor = 0\n    def sumar(self):\n        self.valor += 1\n\nc = Contador()\nc.sumar()\nprint(c.valor)", output: "1", explanation: "Al crear c, su valor empieza en 0. El método sumar actualiza el atributo de c a 1.", caution: "Una variable local sin self no guarda el estado del objeto entre llamadas." },
  u13: { concept: "Un módulo agrupa herramientas listas para usar. import pone sus nombres a tu disposición.", steps: ["import carga el módulo; también puedes darle un alias con as.", "Llama sus funciones con módulo.función para que el origen quede claro.", "La biblioteca estándar viene con Python; pip instala paquetes externos en otros entornos."], code: "import math\nprint(math.sqrt(81))\nprint(math.ceil(2.1))", output: "9.0\n3", explanation: "sqrt calcula la raíz y devuelve un float; ceil redondea hacia el entero superior.", caution: "Importar una librería externa requiere tenerla instalada en el entorno donde ejecutas el código." },
  p0: { concept: "Un análisis pequeño ya puede contar una historia: centro y extremo de una lista de datos.", steps: ["Define qué representa cada número y cuántos datos tienes.", "Calcula la media como suma dividida entre cantidad.", "Contrasta la media con un extremo para no esconder variaciones."], code: "ventas = [4, 8, 12]\nprint(sum(ventas) / len(ventas))\nprint(max(ventas))", output: "8.0\n12", explanation: "El promedio es 8, pero el máximo llega a 12: ese contraste da contexto al resumen.", caution: "len debe ser mayor que cero antes de dividir; una lista vacía no tiene media." },
  u14: { concept: "Un array de NumPy tiene forma (shape), tipo de dato (dtype) y permite operar sobre muchos valores a la vez.", steps: ["np.array convierte una secuencia en array.", "shape revela dimensiones y tamaño por eje.", "Una operación como * 2 se aplica elemento por elemento."], code: "import numpy as np\na = np.array([2, 4, 6])\nprint(a.shape)\nprint((a * 2).tolist())", output: "(3,)\n[4, 8, 12]", explanation: "El array tiene tres valores en una dimensión. Cada valor se multiplica por 2 sin escribir un for.", caution: "La suma de listas concatena; la suma de arrays opera por elementos compatibles." },
  u15: { concept: "Indexar elige una posición; un slice elige un tramo; una máscara booleana filtra por condición.", steps: ["[0] selecciona el primer elemento.", "[1:3] incluye posiciones 1 y 2, pero excluye 3.", "La comparación crea una máscara True/False que puedes aplicar al array."], code: "import numpy as np\na = np.array([3, 6, 9, 12])\nprint(a[1:3].tolist())\nprint(a[a > 6].tolist())", output: "[6, 9]\n[9, 12]", explanation: "El tramo devuelve 6 y 9; el filtro conserva únicamente los valores superiores a 6.", caution: "El extremo final de un slice nunca forma parte del resultado." },
  u16: { concept: "Vectorizar opera sobre arrays completos; broadcasting adapta formas compatibles sin escribir bucles.", steps: ["Una operación sobre un array se aplica a todos sus elementos.", "Un escalar se puede combinar con cada elemento por broadcasting.", "np.where elige por elemento según una condición."], code: "import numpy as np\na = np.array([1, 4, 7])\nprint((a + 2).tolist())\nprint(np.where(a > 3, 'alto', 'bajo').tolist())", output: "[3, 6, 9]\n['bajo', 'alto', 'alto']", explanation: "El 2 se suma a cada elemento; where selecciona una etiqueta para cada posición.", caution: "Broadcasting necesita formas compatibles; no empareja arrays arbitrarios." },
  u17: { concept: "Las estadísticas resumen un array; axis decide la dirección de cálculo cuando hay varias dimensiones.", steps: ["mean calcula la media; median resiste mejor los extremos.", "En una matriz, axis=0 resume cada columna.", "axis=1 resume cada fila; pregunta qué representa cada eje."], code: "import numpy as np\na = np.array([[2, 4], [6, 8]])\nprint(a.mean(axis=0).tolist())\nprint(a.mean(axis=1).tolist())", output: "[4.0, 6.0]\n[3.0, 7.0]", explanation: "Por columnas: (2+6)/2 y (4+8)/2. Por filas: (2+4)/2 y (6+8)/2.", caution: "No confundas axis=0 con seleccionar la primera fila; reduce ese eje." },
  u18: { concept: "reshape cambia la forma de un array sin crear datos; las máscaras eligen las celdas que cumplen una regla.", steps: ["El producto de las dimensiones nuevas debe coincidir con el número de celdas.", "reshape devuelve una vista o un array con otra forma.", "Una comparación genera True/False para filtrar valores."], code: "import numpy as np\na = np.array([1, 2, 3, 4])\nm = a.reshape(2, 2)\nprint(m.tolist())\nprint(a[a > 2].tolist())", output: "[[1, 2], [3, 4]]\n[3, 4]", explanation: "Cuatro celdas caben en dos filas por dos columnas; la máscara selecciona 3 y 4.", caution: "reshape(3, 2) fallaría porque seis posiciones no pueden almacenar solo cuatro valores." },
  p1: { concept: "Una serie de temperaturas permite comparar días, detectar extremos y justificar un resumen numérico.", steps: ["Conserva juntos los días y las temperaturas en el mismo orden.", "Calcula media y máximo para hablar de lo habitual y lo extremo.", "Recupera la posición del máximo para nombrar el día."], code: "dias = ['Lun', 'Mar', 'Mié']\ntemperaturas = [18, 23, 20]\nprint(sum(temperaturas) / len(temperaturas))\nprint(dias[temperaturas.index(max(temperaturas))])", output: "20.333333333333332\nMar", explanation: "La media resume los tres días; index(max(...)) señala la posición del día más cálido.", caution: "No pierdas la relación entre cada posición de días y su temperatura." },
  u19: { concept: "Matplotlib dibuja datos: la figura es el lienzo y los ejes son el área donde se colocan las marcas.", steps: ["Elige barras para categorías y líneas para una secuencia ordenada.", "fig, ax = plt.subplots() crea el lienzo y el área del gráfico.", "Añade título y etiquetas para que el gráfico se entienda fuera del ejercicio."], code: "import matplotlib.pyplot as plt\nfig, ax = plt.subplots()\nax.bar(['A', 'B'], [3, 5])\nax.set_title('Ventas por grupo')\nprint('B supera a A por', 5 - 3)", output: "B supera a A por 2", explanation: "Cada barra compara una categoría; el título explica qué magnitud representa. La línea print verbaliza la diferencia.", caution: "Un gráfico sin unidades o etiquetas puede llevar a interpretar mal las cantidades." },
  u20: { concept: "Personalizar un gráfico consiste en comunicar mejor: título, unidades, límites y leyenda deben ayudar a leerlo.", steps: ["El título responde qué se compara y por qué importa.", "Las etiquetas indican las unidades reales de cada eje.", "Usa una leyenda cuando dos series comparten el mismo gráfico."], code: "import matplotlib.pyplot as plt\nfig, ax = plt.subplots()\nax.plot([1, 2], [4, 7], label='Ventas')\nax.set(xlabel='Semana', ylabel='Unidades', title='Las ventas crecieron')\nax.legend()\nprint('Cambio:', 7 - 4)", output: "Cambio: 3", explanation: "El título ofrece el hallazgo, la etiqueta aclara la unidad y la leyenda identifica la serie.", caution: "Un eje truncado puede exagerar cambios pequeños; revisa siempre sus límites." },
  u21: { concept: "Seaborn transforma columnas con nombre de una tabla en gráficos estadísticos legibles.", steps: ["data recibe el DataFrame que contiene los datos.", "x e y reciben nombres de columnas, no listas de índices.", "hue separa grupos con colores si esa distinción ayuda a responder la pregunta."], code: "import pandas as pd\nimport seaborn as sns\ndf = pd.DataFrame({'grupo': ['A', 'B'], 'valor': [3, 5]})\nsns.barplot(data=df, x='grupo', y='valor')\nprint(df.loc[df['valor'].idxmax(), 'grupo'])", output: "B", explanation: "El gráfico usa las columnas grupo y valor; idxmax encuentra la fila con valor mayor.", caution: "Más colores no siempre ayudan: usa hue solo cuando la categoría adicional aporta una comparación." },
  u22: { concept: "Una visualización cuenta una historia cuando conecta un dato, su contexto y una conclusión verificable.", steps: ["Elige una sola pregunta antes de elegir el gráfico.", "Muestra la unidad y el denominador de cualquier porcentaje.", "Escribe un título que exprese el hallazgo, no solo el nombre de la columna."], code: "casos = 30\ntotal = 120\nporcentaje = casos / total * 100\nprint(f'{casos} de {total}: {porcentaje:.0f}%')", output: "30 de 120: 25%", explanation: "El 25% solo tiene sentido al decir que se calculó con 120 casos.", caution: "30 de 40 sería 75%: el mismo numerador no representa el mismo resultado." },
  p2: { concept: "Un dashboard pequeño reúne vistas complementarias para responder una pregunta con datos comparables.", steps: ["Define qué mide cada panel antes de dibujarlo.", "Un histograma muestra la distribución; barras comparan categorías.", "Revisa escalas y etiquetas antes de afirmar cuál grupo destaca."], code: "import matplotlib.pyplot as plt\nfig, ejes = plt.subplots(1, 2)\nejes[0].hist([2, 3, 3, 5])\nejes[1].bar(['A', 'B'], [2, 4])\nprint('Paneles:', len(ejes))", output: "Paneles: 2", explanation: "El primer panel resume frecuencias y el segundo compara A y B; responden preguntas diferentes.", caution: "No compares alturas entre paneles con escalas distintas como si fueran la misma medida." },
  u23: { concept: "Una Series es una columna con índice; un DataFrame alinea varias columnas en una tabla.", steps: ["Construye un DataFrame a partir de columnas con nombre.", "Cada fila representa una observación; cada columna, una variable.", "Consulta una columna para obtener una Series."], code: "import pandas as pd\ndf = pd.DataFrame({'nombre': ['Sol', 'Luz'], 'edad': [18, 21]})\nprint(df['edad'].tolist())\nprint(len(df))", output: "[18, 21]\n2", explanation: "La columna edad es una Series; len cuenta las dos filas de la tabla.", caution: "Al crear la tabla, las columnas deben tener longitudes compatibles." },
  u24: { concept: "Seleccionar datos en pandas requiere distinguir etiquetas, posiciones y filtros de filas.", steps: ["df['columna'] elige una columna con nombre.", "loc usa etiquetas; iloc usa posiciones enteras.", "Una condición entre corchetes conserva las filas donde vale True."], code: "import pandas as pd\ndf = pd.DataFrame({'nombre': ['A', 'B'], 'puntos': [4, 9]})\nprint(df.loc[1, 'nombre'])\nprint(df[df['puntos'] > 5]['nombre'].tolist())", output: "B\n['B']", explanation: "loc[1] encuentra la etiqueta de la segunda fila; la máscara conserva solo a B.", caution: "iloc[1] es posición 1; loc[1] es etiqueta 1. No siempre coinciden." },
  u25: { concept: "Limpiar datos es decidir qué hacer con valores ausentes o inválidos y dejar visible esa decisión.", steps: ["Cuenta los nulos antes de eliminarlos o sustituirlos.", "to_numeric con errors='coerce' convierte texto no numérico en NaN.", "Elige una sustitución justificable y vuelve a comprobar el resultado."], code: "import pandas as pd\ns = pd.to_numeric(pd.Series(['4', 'error', '8']), errors='coerce')\nprint(s.isna().sum())\nprint(s.fillna(s.median()).tolist())", output: "1\n[4.0, 6.0, 8.0]", explanation: "'error' pasa a NaN; la mediana de 4 y 8 es 6 y se usa para rellenarlo.", caution: "La imputación altera el conjunto: documenta cuántos valores cambiaste y por qué." },
  u26: { concept: "Transformar una tabla puede crear columnas, mapear categorías o resumir grupos con groupby.", steps: ["Decide qué representa una fila antes de agrupar.", "groupby separa las filas por el valor de una clave.", "Aplica una agregación como sum o mean dentro de cada grupo."], code: "import pandas as pd\ndf = pd.DataFrame({'equipo': ['A', 'B', 'A'], 'venta': [2, 3, 5]})\nprint(df.groupby('equipo')['venta'].sum().to_dict())", output: "{'A': 7, 'B': 3}", explanation: "A reúne las ventas 2 y 5; B tiene 3. El resumen conserva una cifra por equipo.", caution: "Una media por grupo y una suma por grupo cuentan historias distintas; escoge según la pregunta." },
  u27: { concept: "Una serie temporal necesita fechas reales y ordenadas para calcular diferencias, ventanas y periodos.", steps: ["Convierte texto de fecha con pd.to_datetime.", "Ordena cronológicamente antes de aplicar diff o rolling.", "Separa entrenamiento y prueba por tiempo para no utilizar datos futuros."], code: "import pandas as pd\ndf = pd.DataFrame({'fecha': ['2025-01-01', '2025-01-02'], 'valor': [10, 13]})\ndf['fecha'] = pd.to_datetime(df['fecha'])\nprint(df['valor'].diff().iloc[1])", output: "3.0", explanation: "La diferencia entre el segundo valor y el primero es 13 - 10 = 3.", caution: "Una cadena que parece una fecha no se comporta como fecha hasta convertirla." },
  p3: { concept: "Un análisis exploratorio compara grupos sin esconder el tamaño de cada grupo ni confundir asociación con causa.", steps: ["Limpia y define la variable que vas a comparar.", "Agrupa por categoría y calcula tamaño y proporción.", "Explica el hallazgo con cifras y limita la conclusión a esos datos."], code: "import pandas as pd\ndf = pd.DataFrame({'clase': ['A', 'A', 'B'], 'sobrevive': [1, 0, 1]})\nprint(df.groupby('clase')['sobrevive'].mean().to_dict())", output: "{'A': 0.5, 'B': 1.0}", explanation: "A tiene una supervivencia de 1 entre 2; B, de 1 entre 1. La muestra de B es muy pequeña.", caution: "Una tasa de 100% basada en una sola persona no prueba una regla general." },
  u28: { concept: "La estadística descriptiva resume tamaño, centro y dispersión para que un dato no cuente la historia entera.", steps: ["n es la cantidad de observaciones.", "La media y la mediana describen el centro de formas distintas.", "El rango y los cuartiles muestran cuánto varían los valores."], code: "import statistics as s\ndatos = [2, 3, 4, 19]\nprint(len(datos))\nprint(s.mean(datos))\nprint(s.median(datos))", output: "4\n7\n3.5", explanation: "El 19 eleva la media a 7, mientras la mediana queda en 3.5. Ambas cifras son verdaderas.", caution: "No presentes una media sin mencionar los extremos cuando pueden distorsionarla." },
  u29: { concept: "Una distribución describe cómo se reparten los valores; sus parámetros indican centro y variación.", steps: ["Observa el histograma para ver simetría, huecos y extremos.", "En una normal, la media centra y la desviación estándar controla la dispersión.", "En una Bernoulli, p es la probabilidad de un resultado 1."], code: "import statistics as s\ndatos = [4, 5, 6]\nprint(s.mean(datos))\nprint(round(s.pstdev(datos), 2))", output: "5\n0.82", explanation: "Los datos se centran en 5 y se separan poco de esa media; la desviación estándar poblacional es aproximadamente 0.82.", caution: "No declares que los datos son normales solo porque has calculado una media." },
  u30: { concept: "La correlación resume asociación lineal; la covarianza conserva la escala de las variables.", steps: ["Compara pares de valores para ver si suben o bajan juntos.", "r de Pearson va de -1 a 1; cerca de 0 indica poca asociación lineal.", "Dibuja los puntos y evita atribuir causalidad a la correlación."], code: "import numpy as np\nx = [1, 2, 3]\ny = [2, 4, 6]\nprint(round(float(np.corrcoef(x, y)[0, 1]), 2))", output: "1.0", explanation: "Al duplicarse x para obtener y, los pares caen exactamente en una recta ascendente.", caution: "r = 1 no demuestra que x cause y; puede haber otros factores." },
  u31: { concept: "Una prueba de hipótesis compara los datos con una hipótesis nula bajo un procedimiento definido antes de mirar el resultado.", steps: ["H0 representa el punto de partida; H1 expresa la alternativa.", "El p-valor mide cuán extremos serían datos como estos si H0 fuera cierta.", "Compara con un umbral elegido previamente y comunica tamaño de muestra y efecto."], code: "p_valor = 0.03\nalfa = 0.05\nprint(p_valor < alfa)\nprint('Rechazar H0' if p_valor < alfa else 'No rechazar H0')", output: "True\nRechazar H0", explanation: "0.03 cae por debajo del umbral 0.05; esa regla indica rechazar H0 en este ejemplo.", caution: "El p-valor no es la probabilidad de que H0 sea verdadera ni el tamaño del efecto." },
  p4: { concept: "Un informe estadístico necesita números verificables, contexto de la muestra y una conclusión medida.", steps: ["Cuenta n y define de dónde salen los datos.", "Compara media y mediana para detectar extremos influyentes.", "Redacta una frase que explique el resultado y sus límites."], code: "import statistics as s\nx = [2, 3, 4, 11]\nprint(f'n={len(x)}')\nprint(f'media={s.mean(x)}, mediana={s.median(x)}')", output: "n=4\nmedia=5, mediana=3.5", explanation: "La media supera la mediana por un valor alto; n=4 advierte que la muestra es pequeña.", caution: "Una conclusión sin tamaño de muestra o sin contexto es difícil de evaluar." },
  u32: { concept: "Machine Learning ajusta una regla a ejemplos X e y para predecir casos nuevos; hay que compararla con una base simple.", steps: ["X contiene las características y y el valor a predecir.", "Separa ejemplos para evaluar si la regla generaliza.", "Calcula primero un baseline, como predecir siempre la clase mayoritaria."], code: "etiquetas = [1, 1, 0, 1]\nbaseline = max(set(etiquetas), key=etiquetas.count)\nprint(baseline)\nprint(sum(y == baseline for y in etiquetas) / len(etiquetas))", output: "1\n0.75", explanation: "La clase 1 aparece tres de cuatro veces: un modelo que siempre dice 1 ya acierta el 75% en estos datos.", caution: "Una puntuación alta no impresiona si no supera una referencia sencilla en datos no vistos." },
  u33: { concept: "Preprocesar prepara entradas comparables; cualquier estadística aprendida se calcula solo con entrenamiento.", steps: ["Separa train y test antes de ajustar transformaciones.", "Aprende medias, categorías o escalas usando únicamente train.", "Aplica la misma transformación a test sin volver a ajustarla."], code: "train = [2, 4, 6]\ntest = [8]\nmedia_train = sum(train) / len(train)\nprint(media_train)\nprint(test[0] - media_train)", output: "4.0\n4.0", explanation: "La media 4 se aprende de train. El 8 de test solo se transforma con ese dato ya fijado.", caution: "Si calculas la media con test incluido, introduces información futura en el entrenamiento." },
  u34: { concept: "La regresión lineal predice números; la logística transforma una combinación lineal en probabilidad de clase.", steps: ["La expresión w·x + b combina entrada, peso y sesgo.", "En lineal, esa combinación es la predicción numérica.", "En logística, una sigmoide produce una probabilidad y un umbral la convierte en clase."], code: "peso, sesgo, x = 2, 1, 3\nprediccion = peso * x + sesgo\nprint(prediccion)\nprint(peso * 4 + sesgo)", output: "7\n9", explanation: "Con peso 2, cada unidad adicional de x suma 2 a la predicción; el sesgo añade 1.", caution: "Una probabilidad logística y una predicción lineal no tienen el mismo significado." },
  u35: { concept: "Un árbol divide datos por condiciones; un bosque combina varios árboles para reducir la dependencia de una sola división.", steps: ["Cada nodo pregunta si una característica cumple un umbral.", "Sigue una rama hasta una predicción en una hoja.", "Un Random Forest combina predicciones de muchos árboles."], code: "def clasificar(edad):\n    return 'adulto' if edad >= 18 else 'menor'\nprint(clasificar(16))\nprint(clasificar(21))", output: "menor\nadulto", explanation: "Este árbol mínimo solo tiene una división: edad >= 18. Cada caso termina en una hoja diferente.", caution: "Si una característica revela la respuesta porque contiene datos filtrados del futuro, el árbol puede aprovechar esa fuga." },
  u36: { concept: "KNN predice por vecinos cercanos; SVM busca una frontera con margen. Ambos dependen de cómo mides distancia.", steps: ["Escala las variables para evitar que una unidad grande domine la distancia.", "KNN busca k puntos cercanos y decide por sus etiquetas.", "SVM intenta separar clases dejando el mayor margen posible."], code: "puntos = [(1, 'A'), (7, 'B')]\nnuevo = 2\nvecino = min(puntos, key=lambda p: abs(p[0] - nuevo))\nprint(vecino[1])", output: "A", explanation: "El punto 2 está a distancia 1 de A y 5 de B; un KNN de un vecino escogería A.", caution: "No compares distancias entre edad y salario sin ajustar sus escalas." },
  u37: { concept: "K-Means reúne puntos alrededor de k centroides: asigna, recalcula centros y repite.", steps: ["Elige k, la cantidad de grupos que quieres buscar.", "Asigna cada punto al centro más cercano.", "Calcula la media de cada grupo para actualizar el centro."], code: "grupo_a = [2, 4, 6]\ngrupo_b = [10, 12]\nprint(sum(grupo_a) / len(grupo_a))\nprint(sum(grupo_b) / len(grupo_b))", output: "4.0\n11.0", explanation: "Los centroides actualizados quedan en 4 y 11, las medias de los valores asignados a cada grupo.", caution: "El algoritmo no descubre por sí solo cuántos grupos tienen sentido; tú eliges k y evalúas." },
  u38: { concept: "Evaluar un modelo exige elegir una métrica que refleje el coste de sus errores y compararla con un baseline.", steps: ["Cuenta TP, FP, TN y FN en una matriz de confusión.", "Precision pregunta qué parte de los positivos predichos era correcta.", "Recall pregunta qué parte de los positivos reales encontraste."], code: "tp, fp, fn = 8, 2, 4\nprint(tp / (tp + fp))\nprint(round(tp / (tp + fn), 2))", output: "0.8\n0.67", explanation: "Precision es 8 de 10 predicciones positivas; recall es 8 de 12 positivos reales.", caution: "Accuracy puede ocultar muchos falsos negativos si una clase es rara." },
  p5: { concept: "Un proyecto predictivo empieza con un baseline, prueba una regla y compara ambos en los mismos ejemplos.", steps: ["Define la entrada y qué predicción quieres obtener.", "Prepara una regla simple que puedas revisar a mano.", "Cuenta aciertos y errores y contrasta contra la referencia inicial."], code: "valores = [2, 7, 3, 9]\nreales = [0, 1, 0, 1]\npredichos = [int(x > 5) for x in valores]\nprint(predichos)\nprint(sum(a == b for a, b in zip(reales, predichos)))", output: "[0, 1, 0, 1]\n4", explanation: "La regla x > 5 acierta estos cuatro casos de ejemplo. Queda por comprobar si funciona en datos nuevos.", caution: "Acertar en los mismos datos usados para diseñar la regla no demuestra generalización." },
  u39: { concept: "Una neurona combina entradas y pesos, suma un sesgo y aplica una función de activación.", steps: ["Multiplica cada entrada por su peso.", "Suma los productos y el sesgo.", "ReLU convierte los negativos en 0 y conserva los positivos."], code: "entradas = [2, 3]\npesos = [1, -1]\nz = sum(x * w for x, w in zip(entradas, pesos)) + 2\nprint(z)\nprint(max(0, z))", output: "1\n1", explanation: "La suma ponderada es 2 - 3 + 2 = 1; ReLU conserva 1 porque es positivo.", caution: "Una sola neurona lineal no puede representar todos los patrones; la activación aporta no linealidad." },
  u40: { concept: "Keras y PyTorch organizan capas y entrenamiento; aquí ves la misma operación básica con NumPy.", steps: ["forward calcula la salida a partir de entradas y pesos.", "loss cuantifica la diferencia con el objetivo.", "backward obtiene gradientes y step actualiza pesos en un entrenamiento real."], code: "import numpy as np\nx = np.array([2, 3])\nw = np.array([0.5, 1.0])\nprediccion = np.dot(x, w)\nprint(prediccion)\nprint((prediccion - 5) ** 2)", output: "4.0\n1.0", explanation: "El producto escalar es 2×0.5 + 3×1 = 4; frente al objetivo 5, el error cuadrático es 1.", caution: "Este navegador practica el álgebra con NumPy; el ejemplo no ejecuta Keras ni PyTorch." },
  u41: { concept: "Entrenar consiste en actualizar parámetros para reducir una pérdida y luego comprobar si generalizan.", steps: ["Calcula la predicción y la pérdida.", "El gradiente indica cómo cambia la pérdida cuando cambia un peso.", "Resta tasa_de_aprendizaje × gradiente para actualizarlo."], code: "peso = 3.0\ngradiente = 2 * (peso - 1)\ntasa = 0.1\npeso -= tasa * gradiente\nprint(round(peso, 2))", output: "2.6", explanation: "El gradiente vale 4 y el paso resta 0.4; el peso se acerca al objetivo 1.", caution: "Reducir el error de entrenamiento no garantiza mejorar la prueba con datos nuevos." },
  u42: { concept: "Una imagen digital es una matriz de píxeles; el modelo debe interpretar su forma y su escala.", steps: ["MNIST usa imágenes de 28 por 28 píxeles en escala de grises.", "Cada píxel tiene intensidad, por ejemplo de 0 a 255.", "Aplanar una imagen produce 784 entradas, pero conserva la cantidad de datos."], code: "import numpy as np\nimagen = np.zeros((28, 28))\nimagen[0, 0] = 255\nprint(imagen.shape)\nprint(imagen.reshape(-1).size)", output: "(28, 28)\n784", explanation: "28 × 28 = 784. reshape cambia cómo se accede a los datos sin agregar píxeles.", caution: "Antes de comparar imágenes, comprueba si todas usan el mismo rango de intensidades." },
  u43: { concept: "En NLP conviertes texto en partes y después en una representación que un algoritmo puede usar.", steps: ["Tokenizar separa el texto en unidades como palabras.", "Normalizar puede unificar mayúsculas y minúsculas.", "Un vocabulario sencillo registra palabras únicas; otros modelos conservan más información."], code: "texto = 'Python ama datos'\ntokens = texto.lower().split()\nprint(tokens)\nprint(len(set(tokens)))", output: "['python', 'ama', 'datos']\n3", explanation: "lower evita diferencias por mayúsculas y split separa por espacios; el set cuenta tres palabras únicas.", caution: "split no resuelve por sí solo puntuación, idiomas o significado: es un primer paso simplificado." },
  p6: { concept: "Un clasificador pequeño puede explicarse con sus entradas, pesos, regla y resultados.", steps: ["Define un conjunto de puntos y sus etiquetas esperadas.", "Calcula una puntuación con pesos y sesgo.", "Aplica un umbral y cuenta aciertos en puntos separados para evaluación."], code: "puntos = [(0, 0), (0, 1), (1, 0), (1, 1)]\npredicciones = [int(x + y >= 1) for x, y in puntos]\nprint(predicciones)", output: "[0, 1, 1, 1]", explanation: "La regla requiere al menos una entrada igual a 1; por eso solo (0, 0) produce clase 0.", caution: "Explica qué hizo la regla antes de llamarla un modelo útil para el mundo real." },
  boss1: { concept: "Un EDA defendible limpia datos, resume una muestra y convierte las cifras en un hallazgo preciso.", steps: ["Identifica valores ausentes y documenta las filas válidas.", "Calcula tamaño, media y mediana con el mismo subconjunto.", "Redacta una conclusión que no prometa más de lo que esos datos muestran."], code: "import statistics as s\nmuestra = [1, 2, 3, 10]\nprint(len(muestra))\nprint(s.mean(muestra), s.median(muestra))", output: "4\n4 2.5", explanation: "El 10 empuja la media a 4 mientras la mediana queda en 2.5; ese contraste es un hallazgo concreto.", caution: "No escondas el tamaño de la muestra ni confundas una descripción con una predicción." },
  boss2: { concept: "Visualizar y modelar une una referencia simple, un gráfico honesto y una predicción comprobable.", steps: ["Establece una referencia como la media de entrenamiento.", "Elige un gráfico que represente la pregunta y etiquétalo.", "Calcula a mano una predicción del modelo y compara errores."], code: "x = [1, 2, 3]\ny = [3, 5, 7]\nbaseline = sum(y) / len(y)\nprint(baseline)\nprint(2 * 4 + 1)", output: "5.0\n9", explanation: "La media 5 es la referencia; la regla y = 2x + 1 predice 9 para x=4.", caution: "Una recta que coincide con tres puntos necesita evaluación en datos no usados para ajustarla." },
  boss3: { concept: "Un proyecto de portafolio permite reproducir los pasos y comprobar de dónde salió cada afirmación.", steps: ["Declara la fuente, las columnas y el tamaño de la muestra.", "Documenta limpieza, cálculo, comparación y conclusión.", "Guarda código y resultados para que otra persona pueda repetir el proceso."], code: "datos = [3, 5, 7]\nn = len(datos)\nmedia = sum(datos) / n\nprint(f'n={n}; media={media:.1f}')", output: "n=3; media=5.0", explanation: "La frase conserva el tamaño de muestra y el cálculo. Es un primer resultado reproducible.", caution: "No publiques un hallazgo sin decir qué datos y qué pasos produjeron esa cifra." },
};

export function getLessonGuide(unitId: string): LessonGuide | undefined {
  return LESSON_GUIDES[unitId];
}
