import type { LibraryBlock } from "./library";

function guide(prerequisite: string, recipe: string[], pitfalls: string[], question: string): LibraryBlock[] {
  return [
    { type: "h", text: "Antes de resolver" },
    { type: "p", text: prerequisite },
    { type: "h", text: "Cómo pensar el problema" },
    { type: "list", items: recipe },
    { type: "h", text: "Errores que conviene reconocer" },
    { type: "list", items: pitfalls },
    { type: "callout", tone: "idea", text: question },
  ];
}

export const REASONING_GUIDES: Record<string, LibraryBlock[]> = {
  u1: guide('Un programa separa instrucciones, valores y salida. No necesitas instalar nada para los ejemplos de este taller.',
    ['Lee el objetivo: qué texto o número debe aparecer.', 'Distingue texto literal entre comillas de un nombre de variable.', 'Escribe una instrucción por línea y predice la salida antes de ejecutar.'],
    ['print(Hola) busca una variable; print("Hola") muestra texto.', 'Un comentario con # no produce salida.', 'La consola no muestra las comillas que delimitan un string.'], '¿Qué cambia al ejecutar print(7) y print("7")? La salida se ve igual, pero los tipos son distintos.'),
  u2: guide('Comprende primero = como asignación. La parte derecha se evalúa antes de actualizar el nombre de la izquierda.',
    ['Nombra los datos de entrada.', 'Identifica el tipo que necesita cada operación.', 'Calcula el resultado y guárdalo si lo usarás después.', 'Usa print para observarlo; imprimir y guardar son acciones diferentes.'],
    ['"12" es texto; 12 es entero.', 'x = x + 1 necesita que x ya exista.', 'True y False comienzan con mayúscula.'], 'Si precio pasa de 10 a 12, ¿qué variable necesitas recalcular? Cambiar una entrada no actualiza automáticamente un total calculado antes.'),
  u3: guide('Distingue operaciones aritméticas de comparaciones. Una comparación devuelve un booleano.',
    ['Resuelve primero los paréntesis.', 'Aplica la prioridad de operadores.', 'Evalúa cada comparación.', 'Combina sus booleanos con and, or o not.'],
    ['= asigna; == compara.', '> excluye el límite; >= lo incluye.', '7 / 2 es 3.5; 7 // 2 es 3.', 'Con floats, compara con una tolerancia cuando el objetivo sea numérico.'], 'Prueba el valor del límite, uno menor y uno mayor. Es una forma rápida de detectar errores en una condición.'),
  u4: guide('Un string es una secuencia inmutable: sus métodos producen nuevos valores.',
    ['Identifica el texto original.', 'Decide qué transformación necesitas.', 'Guarda el string devuelto si lo usarás más tarde.', 'Compara original y resultado.'],
    ['lower() no cambia una variable sin reasignación.', 'El slice s[1:3] excluye el índice 3.', 'Los espacios dentro del texto son parte del valor.'], '¿Necesitas normalizar un identificador o conservar cómo lo escribió la persona? Decide eso antes de borrar mayúsculas o signos.'),
  u5: guide('Una lista tiene orden y puede cambiar. El primer índice es 0.',
    ['Cuenta cuántos elementos tiene.', 'Identifica qué índice corresponde al elemento deseado.', 'Distingue una operación que modifica la lista de una que devuelve otra.', 'Observa la lista después de cada cambio.'],
    ['append devuelve None; no hagas lista = lista.append(x).', 'lista[-1] selecciona el último elemento.', 'b = a comparte la misma lista; a.copy() crea una copia superficial.'], 'Antes de quitar elementos mientras recorres una lista, piensa si los índices cambiarán.'),
  u8: guide('Una condición decide qué bloque se ejecuta. La indentación señala qué instrucciones pertenecen a ese bloque.',
    ['Escribe la condición con sus límites.', 'Evalúala para los datos concretos.', 'Sigue solo la rama elegida.', 'Continúa con las líneas que quedan fuera del bloque.'],
    ['Los dos puntos son necesarios.', 'En if/elif/else se ejecuta la primera rama verdadera.', 'Dos if separados pueden ejecutar dos bloques.'], 'Comprueba tres casos: dentro de la condición, fuera y exactamente en el límite.'),
  u9: guide('Un bucle repite instrucciones. Un acumulador conserva un resultado parcial entre iteraciones.',
    ['Inicializa el acumulador antes del bucle.', 'Anota el elemento actual.', 'Actualiza el acumulador usando su valor anterior.', 'Imprime después del bucle si quieres solo el total.'],
    ['Inicializar total = 0 dentro del bucle borra el resultado anterior.', 'range(3) produce 0, 1 y 2.', 'En while, debe existir una actualización que permita salir.'], 'Haz una tabla con iteración, elemento y total. Si puedes seguirla a mano con tres datos, comprenderás el bucle.'),
  u10: guide('Definir una función guarda una receta; llamarla ejecuta esa receta con argumentos concretos.',
    ['Identifica entradas y salida.', 'Escribe una función con una responsabilidad clara.', 'Usa return para entregar el resultado.', 'Llama la función y guarda lo que devuelve.'],
    ['print muestra; return entrega un valor al programa.', 'Sin return explícito, una función devuelve None.', 'Un parámetro recibe el valor del argumento; sus nombres no necesitan coincidir.'], '¿Puedes usar la salida como entrada de otro cálculo? Si solo la imprimiste, quizá necesites devolverla.'),
  u13: guide('Un módulo es código ya escrito. Su API te dice cómo usarlo sin leer todo el archivo.',
    ['Identifica el módulo: math, statistics, numpy.', 'Lee el nombre de la función y qué argumento pide.', 'Anota qué tipo devuelve: int, float, lista, None.', 'Impórtalo y llama módulo.función(argumento).'],
    ['from modulo import * esconde de dónde sale cada nombre.', 'El alias as no cambia la función, solo el mote.', 'Si la ficha dice que devuelve float, int() es un paso aparte.'], 'math.sqrt(16) devuelve 4.0, no 4. ¿Qué línea extra necesitas si el enunciado pide un entero?'),
  u14: guide('Un array NumPy guarda datos con una forma y un tipo. No se comporta igual que una lista de Python.',
    ['Mira shape, size y dtype.', 'Decide si necesitas una operación por elemento o una reducción.', 'Predice la forma de la salida.', 'Contrasta el resultado con un ejemplo pequeño.'],
    ['[2, 4] * 2 repite una lista; np.array([2, 4]) * 2 multiplica sus valores.', 'size cuenta celdas; shape describe dimensiones.', 'Un array no cambia automáticamente de forma porque cambie el significado de sus datos.'], 'Antes de una operación, predice tanto los valores como las dimensiones del resultado.'),
  u18: guide('Una máscara booleana contiene una decisión por posición: conservar True y descartar False.',
    ['Escribe la condición para un solo valor.', 'Aplícala al array completo.', 'Inspecciona la máscara.', 'Usa esa máscara dentro de los corchetes del array.'],
    ['a > 0 excluye cero.', 'Para combinar máscaras usa (condición1) & (condición2).', 'and no sirve para decidir elemento a elemento en un array.'], 'No confundas el array booleano con los valores filtrados: son resultados diferentes.'),
  u23: guide('Un DataFrame organiza observaciones en filas y variables en columnas. Inspecciona la tabla antes de calcular.',
    ['Mira head() y shape.', 'Comprueba los nombres de columnas.', 'Revisa tipos y valores ausentes.', 'Selecciona la columna y calcula la métrica que responde tu pregunta.'],
    ['len(df) cuenta filas.', 'df["ventas"] devuelve una Series; df[["ventas"]] mantiene un DataFrame.', 'Una cifra con tipo texto necesita conversión antes de operaciones numéricas.'], '¿Cada fila representa un cliente, una venta o un día? El significado de una media depende de eso.'),
  u25: guide('Limpiar es tomar decisiones sobre datos problemáticos. No todas las columnas deben rellenarse con cero.',
    ['Cuenta nulos y duplicados.', 'Distingue valores imposibles de casos raros pero reales.', 'Elige y documenta la regla de limpieza.', 'Comprueba cuántas filas y nulos quedan.'],
    ['La mediana de una columna completamente vacía también es un valor ausente.', 'Eliminar filas cambia la muestra y puede introducir sesgo.', 'Un booleano de NumPy no tiene que ser el objeto Python True; comprueba su valor.'], '¿Por qué elegiste mediana en lugar de media? Explica cómo afectan los valores extremos.'),
  u26: guide('Agrupar resume observaciones; combinar tablas añade información mediante una clave.',
    ['Define qué representa cada grupo.', 'Selecciona la columna que resumirás.', 'Elige suma, media, conteo u otra métrica.', 'Verifica que el resultado tenga una fila por grupo esperado.'],
    ['count omite nulos; size cuenta filas.', 'Un merge con claves repetidas puede multiplicar filas.', 'Una media de medias no suele equivaler a la media de todas las observaciones.'], 'Si unas ciudades tienen más registros que otras, ¿quieres dar el mismo peso a cada ciudad o a cada registro?'),
  u28: guide('Una estadística resume un aspecto de los datos. Centro y dispersión responden preguntas distintas.',
    ['Observa el tamaño de la muestra y las unidades.', 'Calcula media y mediana para el centro.', 'Usa rango, IQR o desviación para la dispersión.', 'Explica qué oculta el resumen.'],
    ['Un valor extremo puede cambiar mucho la media.', 'La desviación tiene las unidades originales; la varianza tiene unidades al cuadrado.', 'Una muestra pequeña limita la interpretación.'], 'Dos grupos pueden tener la misma media y una dispersión muy distinta. Busca ambos números.'),
  u33: guide('El preprocesamiento forma parte del modelo. Sus parámetros deben aprenderse solo con datos de entrenamiento.',
    ['Separa train y test antes de aprender transformaciones.', 'Ajusta imputación y escalado usando train.', 'Aplica transform sin volver a hacer fit en test.', 'Integra las transformaciones en un pipeline reproducible.'],
    ['Ajustar el escalado con todo el dataset filtra información del test.', 'fit_transform en test cambia la escala aprendida.', 'Una categoría nueva en test necesita una política explícita.'], '¿Tu resultado seguiría siendo válido si los datos de test llegaran mañana y nunca los hubieras visto?'),
  u38: guide('Una métrica necesita una pregunta, un baseline y el coste de los errores.',
    ['Cuenta aciertos, falsos positivos y falsos negativos.', 'Calcula la métrica con su denominador correcto.', 'Compárala con una regla sencilla.', 'Evalúa datos separados del entrenamiento.'],
    ['Accuracy puede engañar con clases muy desbalanceadas.', 'Precisión y recall tienen denominadores distintos.', 'Elegir el modelo mirando repetidamente el test deja de ser una evaluación final.'], 'Si casi todos los casos son negativos, ¿qué accuracy logra un modelo que nunca detecta un positivo?'),
  u39: guide('Una neurona calcula una combinación lineal y después aplica una activación.',
    ['Multiplica cada entrada por su peso.', 'Suma los productos y el sesgo.', 'Aplica la activación.', 'Comprueba el resultado y su forma.'],
    ['El sesgo se suma antes de la activación.', 'ReLU transforma negativos en cero.', 'Un resultado 2.0 y 2 pueden representar la misma cantidad, aunque sus tipos difieran.'], 'Cambia solo el sesgo: ¿cuándo se apaga la neurona con ReLU?'),
  u43: guide('Representar texto exige decidir qué unidades contar y qué información conservar.',
    ['Define cómo separar el texto en tokens.', 'Cuenta apariciones si te interesa frecuencia.', 'Usa valores únicos si te interesa vocabulario.', 'Comprueba qué señales pierde tu representación.'],
    ['Número de tokens y tamaño del vocabulario no son lo mismo.', 'split por espacios no reproduce los tokenizadores de los LLM.', 'Una bolsa de palabras pierde el orden.'], '¿perro muerde hombre y hombre muerde perro tendrán el mismo conteo? Esa limitación importa para entender el significado.'),
};
