import {
  Award,
  BarChart3,
  Bell,
  BookKey,
  BookOpen,
  Box,
  Boxes,
  Brain,
  Calculator,
  Calendar,
  CircleDot,
  Combine,
  Compass,
  Crown,
  Dumbbell,
  FileBarChart,
  Filter,
  Flame,
  FlaskConical,
  Footprints,
  Gem,
  GitBranch,
  GitCompare,
  Grid3x3,
  Hand,
  Hash,
  Image,
  Languages,
  Layers,
  LayoutDashboard,
  LineChart,
  List,
  MessageSquare,
  Network,
  Package,
  Palette,
  Repeat,
  Scroll,
  Scissors,
  ShieldAlert,
  Ship,
  Sigma,
  Sparkle,
  Sparkles,
  SquareFunction,
  Star,
  Stars,
  Swords,
  Table,
  Target,
  Thermometer,
  TreePine,
  TrendingUp,
  Trophy,
  Type,
  Waypoints,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  sparkles: Sparkles,
  box: Box,
  calculator: Calculator,
  type: Type,
  list: List,
  hash: Hash,
  "book-key": BookKey,
  "git-branch": GitBranch,
  repeat: Repeat,
  "square-function": SquareFunction,
  "shield-alert": ShieldAlert,
  boxes: Boxes,
  package: Package,
  trophy: Trophy,
  grid: Grid3x3,
  layers: Layers,
  zap: Zap,
  sigma: Sigma,
  thermometer: Thermometer,
  "line-chart": LineChart,
  palette: Palette,
  "bar-chart-3": BarChart3,
  "message-square": MessageSquare,
  "layout-dashboard": LayoutDashboard,
  table: Table,
  filter: Filter,
  sparkle: Sparkle,
  combine: Combine,
  calendar: Calendar,
  ship: Ship,
  bell: Bell,
  "git-compare": GitCompare,
  "flask-conical": FlaskConical,
  "file-bar-chart": FileBarChart,
  brain: Brain,
  scissors: Scissors,
  "trending-up": TrendingUp,
  "tree-pine": TreePine,
  waypoints: Waypoints,
  circles: CircleDot,
  target: Target,
  network: Network,
  dumbbell: Dumbbell,
  image: Image,
  languages: Languages,
  award: Award,
  swords: Swords,
  crown: Crown,
  scroll: Scroll,
  footprints: Footprints,
  hand: Hand,
  flame: Flame,
  star: Star,
  stars: Stars,
  gem: Gem,
  compass: Compass,
};

export function UnitIcon({ name, className }: { name?: string; className?: string }) {
  const Icon = (name && ICONS[name]) || BookOpen;
  return <Icon className={className} />;
}
