"""Niveles 2–4 para fundamentos tardíos, NumPy y visualización."""


def three(h, uid, rows):
    return {
        uid: [
            h["lesson"](f"{uid}-l{lv}", title, desc, xs, level=lv)
            for lv, title, desc, xs in rows
        ]
    }


def packs(h):
    mc, fill, predict, code, matching, find_err, reorder = (
        h["mc"], h["fill"], h["predict"], h["code"], h["matching"], h["find_err"], h["reorder"],
    )
    out = {}
    out.update(three(h, "u6", [
        (2, "Afianza: fijo vs único", "Separa tupla (no cambia) y set (sin duplicados).", [
            mc("u6-l2-e1", "¿Cuál es la diferencia útil entre tupla y lista?",
               [("a", "La tupla no se puede ampliar ni reescribir por índice"),
                ("b", "La tupla es más lenta siempre"),
                ("c", "La tupla no puede guardar números")],
               "a", "Por eso una tupla sirve como registro fijo: (lat, lon) no debería mutar."),
            predict("u6-l2-e2", "¿Qué imprime?", "print(len({1, 1, 2, 3}))", "3",
                    "El set elimina duplicados: quedan 1, 2 y 3."),
            fill("u6-l2-e3", "Desempaqueta el punto.", "x, y = (4, 9)\nprint(___)", [{"accepted": ["x"]}],
                 "x, y = (4, 9) asigna 4 a x y 9 a y."),
            matching("u6-l2-e4", "Empareja la estructura con el uso.",
                     [{"id": "l1", "text": "Tupla"}, {"id": "l2", "text": "Set"}, {"id": "l3", "text": "Lista"}],
                     [{"id": "r1", "text": "Coordenada o fila que no debe cambiar"},
                      {"id": "r2", "text": "Valores únicos, sin orden garantizado"},
                      {"id": "r3", "text": "Cola de trabajo que sí se edita"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Elige la caja según si el orden importa, si puede mutar y si hay duplicados."),
        ]),
        (3, "Practica: unión e intersección", "Opera conjuntos y deja la tupla intacta.", [
            code("u6-l3-e1",
                 "`a = {1, 2, 3}` y `b = {3, 4}`. Guarda `comun = a & b` e imprime `sorted(comun)`.",
                 "a = {1, 2, 3}\nb = {3, 4}\n",
                 ["comun == {3}"],
                 "a = {1, 2, 3}\nb = {3, 4}\ncomun = a & b\nprint(sorted(comun))",
                 "& es intersección: solo lo que está en los dos sets.",
                 expected_stdout="[3]"),
            predict("u6-l3-e2", "¿Cuántos elementos tiene la unión?", "print(len({1, 2} | {2, 8}))", "3",
                    "| une sin repetir el 2: quedan tres valores."),
            find_err("u6-l3-e3", "¿Qué falla si haces `punto = (3, 4)` y luego `punto.append(5)`?",
                     [("a", "Las tuplas no tienen append: no se mutan"),
                      ("b", "Falta import tuple"),
                      ("c", "append solo funciona con sets")],
                     "a", "Si necesitas crecer, usa una lista. Si es un pack fijo, tupla."),
            mc("u6-l3-e4", "¿Por qué un set no puede guardar una lista?",
               [("a", "Los elementos de un set tienen que ser hashables; una lista cambia"),
                ("b", "Los sets solo admiten strings"),
                ("c", "Python limita los sets a 3 elementos")],
               "a", "Números, strings y tuplas de inmutables sí. Listas no."),
        ]),
        (4, "Demuestra: elige la caja", "Decide estructura según el problema.", [
            mc("u6-l4-e1", "IDs de cliente únicos para un JOIN rápido. ¿Qué usas?",
               [("a", "Un set de IDs"), ("b", "Una tupla de un solo ID"), ("c", "Un string con comas")],
               "a", "Pertenencia `id in vistos` es el gesto del set."),
            code("u6-l4-e2",
                 "`pares = [(0, 1), (1, 0)]`. Crea `primero = pares[0]` e imprime `primero[1]`.",
                 "pares = [(0, 1), (1, 0)]\n",
                 ["primero == (0, 1)"],
                 "pares = [(0, 1), (1, 0)]\nprimero = pares[0]\nprint(primero[1])",
                 "Una lista de tuplas es el formato típico de 'muchos puntos'.",
                 expected_stdout="1"),
            reorder("u6-l4-e3", "Ordena: de lista sucia a valores únicos ordenados.",
                    [{"id": "a", "code": "crudo = [3, 1, 3, 2]"},
                     {"id": "b", "code": "unicos = set(crudo)"},
                     {"id": "c", "code": "limpio = sorted(unicos)"},
                     {"id": "d", "code": "print(limpio)"}],
                    ["a", "b", "c", "d"],
                    "set quita duplicados; sorted vuelve a dar una lista con orden."),
            matching("u6-l4-e4", "Operación de sets.",
                     [{"id": "l1", "text": "a | b"}, {"id": "l2", "text": "a & b"}, {"id": "l3", "text": "a - b"}],
                     [{"id": "r1", "text": "Unión"}, {"id": "r2", "text": "Intersección"}, {"id": "r3", "text": "Lo de a que no está en b"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Es el mismo lenguaje de Venn que usarás al filtrar IDs."),
        ]),
    ]))
    out.update(three(h, "u7", [
        (2, "Afianza: clave y valor", "Un dict se pregunta por nombre, no por puesto.", [
            mc("u7-l2-e1", "En `persona['xp']`, `'xp'` es…",
               [("a", "La clave"), ("b", "El valor"), ("c", "Un índice numérico obligatorio")],
               "a", "La clave identifica; el valor es lo guardado (120, 'Mara'…)."),
            predict("u7-l2-e2", "¿Salida?", 'd = {"a": 1, "b": 2}\nprint(d.get("c", 0))', "0",
                    "get no explota: si falta la clave, usa el default."),
            fill("u7-l2-e3", "Lee el nombre.", 'p = {"nombre": "Noa"}\nprint(p[___])', [{"accepted": ["'nombre'", '"nombre"']}],
                 "Los corchetes piden una clave que exista."),
            find_err("u7-l2-e4", "`p = {'n': 1}` y `print(p['liga'])`. ¿Qué pasa?",
                     [("a", "KeyError: esa clave no está"),
                      ("b", "Imprime None"),
                      ("c", "Imprime 1")],
                     "a", "Usa .get o pregunta `'liga' in p` antes de los corchetes."),
        ]),
        (3, "Practica: actualizar y recorrer", "Cambia un valor y recorre items.", [
            code("u7-l3-e1",
                 '`fila = {"ciudad": "Lima", "xp": 10}`. Suma 5 a xp e imprime el nuevo xp.',
                 'fila = {"ciudad": "Lima", "xp": 10}\n',
                 ["fila['xp'] == 15"],
                 'fila = {"ciudad": "Lima", "xp": 10}\nfila["xp"] += 5\nprint(fila["xp"])',
                 "fila['xp'] += 5 muta el valor de esa clave.",
                 expected_stdout="15"),
            matching("u7-l3-e2", "Método de dict.",
                     [{"id": "l1", "text": ".keys()"}, {"id": "l2", "text": ".values()"}, {"id": "l3", "text": ".items()"}],
                     [{"id": "r1", "text": "Solo las claves"}, {"id": "r2", "text": "Solo los valores"},
                      {"id": "r3", "text": "Pares (clave, valor)"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "for k, v in d.items() es el bucle más útil en datos."),
            predict("u7-l3-e3", "¿Salida?", 'd = {"x": 2}\nd["x"] = d.get("x", 0) + 1\nprint(d["x"])', "3",
                    "get con default 0 también sirve para incrementar si ya existía."),
            mc("u7-l3-e4", "¿Por qué una lista no puede ser clave de un dict?",
               [("a", "Las claves deben ser inmutables/hashables"),
                ("b", "Los dicts solo aceptan ints"),
                ("c", "Python reserva las listas para sets")],
               "a", "String, int y tupla de inmutables sí. Lista no."),
        ]),
        (4, "Demuestra: un registro de datos", "Usa el dict como fila de una tabla.", [
            code("u7-l4-e1",
                 'Crea `fila = {"mes": 3, "unidades": 9}` e imprime `fila["unidades"]`.',
                 "",
                 ["fila == {'mes': 3, 'unidades': 9}"],
                 'fila = {"mes": 3, "unidades": 9}\nprint(fila["unidades"])',
                 "Así se ve una fila antes de Pandas: un dict por observación.",
                 expected_stdout="9"),
            mc("u7-l4-e2", "Tienes 1000 filas como dicts. ¿Qué echas de menos vs un DataFrame?",
               [("a", "Nombres de columna alineados, tipos y operaciones vectorizadas"),
                ("b", "La posibilidad de guardar texto"),
                ("c", "Poder usar un for")],
               "a", "El dict enseña el modelo mental; Pandas lo escala."),
            find_err("u7-l4-e3", "Alguien hace `total = {}` y `total + 1`. ¿El error de fondo?",
                     [("a", "Un dict no se suma como un número; hay que elegir una clave"),
                      ("b", "Los dicts no se pueden crear vacíos"),
                      ("c", "+ está prohibido en Python")],
                     "a", "Suma `total['unidades']`, no el contenedor entero."),
            matching("u7-l4-e4", "Analogía tabla.",
                     [{"id": "l1", "text": "Clave"}, {"id": "l2", "text": "Valor"}, {"id": "l3", "text": "Dict completo"}],
                     [{"id": "r1", "text": "Nombre de columna"}, {"id": "r2", "text": "Celda"}, {"id": "r3", "text": "Una fila"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Cuando llegues a Pandas, cada fila sigue siendo este mapa."),
        ]),
    ]))
    out.update(three(h, "u8", [
        (2, "Afianza: la pregunta del if", "Una condición es sí o no; la indentación marca el bloque.", [
            mc("u8-l2-e1", "¿Cuántos `=` usas para preguntar si x vale 5?",
               [("a", "Dos: x == 5"), ("b", "Uno: x = 5"), ("c", "Tres: x === 5")],
               "a", "Un = guarda. Dos == comparan. El error clásico en if."),
            predict("u8-l2-e2", "¿Qué imprime?", "n = 7\nif n > 10:\n    print('alto')\nelif n > 5:\n    print('medio')\nelse:\n    print('bajo')", "medio",
                    "7 no pasa el primer if; sí pasa elif n > 5."),
            fill("u8-l2-e3", "Completa la comparación.", "if edad ___ 18:\n    print('ok')", [{"accepted": [">=", "=="]}],
                 ">= 18 es 'mayor o igual'. == 18 sería solo ese año exacto."),
            find_err("u8-l2-e4", "`if xs:` con `xs = []`. ¿Entra al bloque?",
                     [("a", "No: una lista vacía cuenta como no"),
                      ("b", "Sí: cualquier lista es True"),
                      ("c", "Solo si tiene strings")],
                     "a", "0, '', [], {}, None son 'falsy'."),
        ]),
        (3, "Practica: ramificar un dato", "Etiqueta un número con if/elif/else.", [
            code("u8-l3-e1",
                 "`score = 82`. Crea `nota = 'alto'` si score >= 80, si no `'bajo'`. Imprime nota.",
                 "score = 82\n",
                 ["nota == 'alto'"],
                 "score = 82\nnota = 'alto' if score >= 80 else 'bajo'\nprint(nota)",
                 "También vale un if/else clásico indentado. 82 cumple >= 80.",
                 expected_stdout="alto"),
            matching("u8-l3-e2", "Palabra del if.",
                     [{"id": "l1", "text": "if"}, {"id": "l2", "text": "elif"}, {"id": "l3", "text": "else"}],
                     [{"id": "r1", "text": "Primera pregunta"},
                      {"id": "r2", "text": "Otra pregunta si las de arriba fallaron"},
                      {"id": "r3", "text": "Plan B si nada se cumplió"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "elif evita anidar diez if sueltos."),
            predict("u8-l3-e3", "¿Salida?", "x = 0\nprint('sí' if x else 'no')", "no",
                    "0 es falsy, así que elige 'no'."),
            mc("u8-l3-e4", "`and` entre dos condiciones significa…",
               [("a", "Las dos tienen que ser True"),
                ("b", "Basta con que una sea True"),
                ("c", "Invierte el resultado")],
               "a", "or es 'al menos una'. not invierte."),
        ]),
        (4, "Demuestra: reglas de negocio", "Traduce una regla en ramas claras.", [
            mc("u8-l4-e1", "Edad 17, regla: >=18 adulto, >=13 teen, resto niño. ¿Qué etiqueta?",
               [("a", "teen"), ("b", "adulto"), ("c", "niño")],
               "a", "El orden de elif importa: si pones >=13 primero, un adulto también sería teen."),
            code("u8-l4-e2",
                 "`temp = -1`. `estado = 'hielo'` si temp < 0, si no `'agua'`. Imprime estado.",
                 "temp = -1\n",
                 ["estado == 'hielo'"],
                 "temp = -1\nestado = 'hielo' if temp < 0 else 'agua'\nprint(estado)",
                 "Umbrales (< 0, >= 0) son el corazón de un if de datos.",
                 expected_stdout="hielo"),
            find_err("u8-l4-e3", "Alguien escribe `if n = 5:`. ¿Por qué es inválido?",
                     [("a", "En un if hace falta comparar (==), no asignar"),
                      ("b", "n no puede ser 5"),
                      ("c", "Los if no usan dos puntos")],
                     "a", "SyntaxError típico al empezar."),
            reorder("u8-l4-e4", "Ordena un clasificador de 3 bandas.",
                    [{"id": "a", "code": "n = 12"},
                     {"id": "b", "code": "if n < 0:\n    etiqueta = 'neg'"},
                     {"id": "c", "code": "elif n == 0:\n    etiqueta = 'cero'"},
                     {"id": "d", "code": "else:\n    etiqueta = 'pos'"}],
                    ["a", "b", "c", "d"],
                    "Primero el dato, luego las preguntas de más específico a catch-all."),
        ]),
    ]))
    out.update(three(h, "u9", [
        (2, "Afianza: repetir sin copiar", "for recorre; range cuenta desde cero.", [
            mc("u9-l2-e1", "`for i in range(3):` ¿cuántas vueltas y qué i?",
               [("a", "3 vueltas: 0, 1, 2"), ("b", "3 vueltas: 1, 2, 3"), ("c", "2 vueltas: 0, 1")],
               "a", "range(n) llega hasta n-1. No incluye n."),
            predict("u9-l2-e2", "¿Salida?", "for x in [2, 4]:\n    print(x)", "2\n4",
                    "for visita cada elemento en orden."),
            fill("u9-l2-e3", "Recorre nombres.", "for n in nombres:\n    print(___)", [{"accepted": ["n"]}],
                 "n es el elemento de esta vuelta, no el índice (salvo que uses enumerate)."),
            matching("u9-l2-e4", "Herramienta de bucle.",
                     [{"id": "l1", "text": "for"}, {"id": "l2", "text": "while"}, {"id": "l3", "text": "break"}],
                     [{"id": "r1", "text": "Recorre una colección conocida"},
                      {"id": "r2", "text": "Repite mientras una condición sea sí"},
                      {"id": "r3", "text": "Sale del bucle ahora"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "while sin cambiar la condición se queda colgado."),
        ]),
        (3, "Practica: acumular", "Un acumulador suma o cuenta dentro del for.", [
            code("u9-l3-e1",
                 "`xs = [3, 1, 4]`. Guarda `total = 0`, súmalos con un for e imprime total.",
                 "xs = [3, 1, 4]\n",
                 ["total == 8"],
                 "xs = [3, 1, 4]\ntotal = 0\nfor x in xs:\n    total += x\nprint(total)",
                 "El acumulador nace en 0 fuera del bucle. sum(xs) es el atajo.",
                 expected_stdout="8"),
            predict("u9-l3-e2", "¿Salida?", "print(list(range(1, 4)))", "[1, 2, 3]",
                    "range(1, 4) incluye 1 y excluye 4."),
            mc("u9-l3-e3", "`continue` hace…",
               [("a", "Salta el resto de esta vuelta y sigue con la siguiente"),
                ("b", "Termina el programa"),
                ("c", "Reinicia Python")],
               "a", "break sale del todo; continue solo de esta iteración."),
            fill("u9-l3-e4", "Cuenta de 0 a 4.", "for i in ___(5):\n    print(i)", [{"accepted": ["range"]}],
                 "range(5) → 0,1,2,3,4."),
        ]),
        (4, "Demuestra: filtrar al vuelo", "Combina for e if para quedarte con un subconjunto.", [
            code("u9-l4-e1",
                 "`xs = [5, 12, 3, 20]`. Crea `altos` con los > 10 e imprime `altos`.",
                 "xs = [5, 12, 3, 20]\n",
                 ["altos == [12, 20]"],
                 "xs = [5, 12, 3, 20]\naltos = [x for x in xs if x > 10]\nprint(altos)",
                 "La comprensión [x for x in xs if …] es el for+if en una línea.",
                 expected_stdout="[12, 20]"),
            find_err("u9-l4-e2", "Un while `n > 0` nunca resta n. ¿Qué ocurre?",
                     [("a", "Bucle infinito: la condición no deja de ser True"),
                      ("b", "Python resta solo"),
                      ("c", "Se convierte en for")],
                     "a", "Algo dentro del while tiene que acercarte al final."),
            matching("u9-l4-e3", "Patrón.",
                     [{"id": "l1", "text": "enumerate"}, {"id": "l2", "text": "zip"}, {"id": "l3", "text": "acumulador"}],
                     [{"id": "r1", "text": "Índice y valor a la vez"},
                      {"id": "r2", "text": "Dos listas en paralelo"},
                      {"id": "r3", "text": "Variable que crece vuelta a vuelta"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "zip(nombres, edades) es el for de una tablita."),
            mc("u9-l4-e4", "En datos, ¿cuándo dejas el for de Python y pasas a NumPy/Pandas?",
               [("a", "Cuando hay muchos números homogéneos y la misma operación a todos"),
                ("b", "Nunca: el for es siempre más rápido"),
                ("c", "Solo si hay strings")],
               "a", "El for enseña la lógica. El array la ejecuta en bloque."),
        ]),
    ]))
    out.update(three(h, "u10", [
        (2, "Afianza: receta con nombre", "def define; return entrega; llamar usa paréntesis.", [
            mc("u10-l2-e1", "Sin `return`, una función Python entrega…",
               [("a", "None"), ("b", "0"), ("c", "Un error siempre")],
               "a", "Si solo hace print, el valor de f() es None."),
            predict("u10-l2-e2", "¿Salida?", "def doble(n):\n    return n * 2\nprint(doble(5))", "10",
                    "5 entra como n; return 10; print lo muestra."),
            fill("u10-l2-e3", "Cabecera de función.", "___ media(xs):\n    return sum(xs) / len(xs)", [{"accepted": ["def"]}],
                 "def abre la receta. Los dos puntos y la indentación son el cuerpo."),
            matching("u10-l2-e4", "Vocabulario.",
                     [{"id": "l1", "text": "Parámetro"}, {"id": "l2", "text": "Argumento"}, {"id": "l3", "text": "return"}],
                     [{"id": "r1", "text": "Nombre en la definición (xs)"},
                      {"id": "r2", "text": "Valor al llamar ([2, 4])"},
                      {"id": "r3", "text": "Sale y entrega un resultado"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Confundir print con return es el bug #1 de funciones."),
        ]),
        (3, "Practica: una función de datos", "Media, máximo o un default.", [
            code("u10-l3-e1",
                 "Define `def maximo(xs):` que devuelva el mayor. Imprime `maximo([2, 9, 4])`.",
                 "",
                 ["maximo([2, 9, 4]) == 9"],
                 "def maximo(xs):\n    return max(xs)\nprint(maximo([2, 9, 4]))",
                 "max ya existe; envolverlo enseña a encapsular.",
                 expected_stdout="9"),
            find_err("u10-l3-e2", "`def f(xs=[]):` y vas haciendo append. ¿El clásico bug?",
                     [("a", "Esa lista default se comparte entre llamadas"),
                      ("b", "Las funciones no admiten listas"),
                      ("c", "append no existe")],
                     "a", "Usa None y crea la lista dentro: `if xs is None: xs = []`."),
            predict("u10-l3-e3", "¿Salida?", "def f(n=3):\n    return n + 1\nprint(f())\nprint(f(10))", "4\n11",
                    "Sin argumento usa 3. Con 10, ignora el default."),
            mc("u10-l3-e4", "¿Para qué sirve una función en un análisis?",
               [("a", "No copiar la misma limpieza o métrica diez veces"),
                ("b", "Hacer que Python ignore errores"),
                ("c", "Sustituir a Pandas")],
               "a", "Un nombre claro (media_sin_nulos) documenta la intención."),
        ]),
        (4, "Demuestra: entrada → cálculo → salida", "Diseña una función que se pueda testear.", [
            code("u10-l4-e1",
                 "`def tasa(ok, n):` devuelve ok/n si n else 0. Imprime `tasa(3, 4)`.",
                 "",
                 ["abs(tasa(3, 4) - 0.75) < 1e-9", "tasa(1, 0) == 0"],
                 "def tasa(ok, n):\n    return ok / n if n else 0\nprint(tasa(3, 4))",
                 "Guardar el 0 cuando n=0 evita ZeroDivisionError.",
                 expected_stdout="0.75"),
            mc("u10-l4-e2", "Un test de función debería comprobar…",
               [("a", "Un ejemplo conocido y un borde (lista vacía, n=0)"),
                ("b", "Solo que no imprima"),
                ("c", "Que el nombre tenga 3 letras")],
               "a", "Los asserts de PyQuest son exactamente eso."),
            matching("u10-l4-e3", "Partes de una buena función de datos.",
                     [{"id": "l1", "text": "Nombre"}, {"id": "l2", "text": "return"}, {"id": "l3", "text": "Docstring"}],
                     [{"id": "r1", "text": "Dice qué calcula"},
                      {"id": "r2", "text": "Permite usarla en otra fórmula"},
                      {"id": "r3", "text": "Explica unidades y supuestos"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "print es para ti; return es para el siguiente cálculo."),
            find_err("u10-l4-e4", "`def media(xs): print(sum(xs)/len(xs))` y luego `y = media(xs) * 2`. ¿Por qué rompe?",
                     [("a", "media entrega None; no puedes multiplicar None"),
                      ("b", "print multiplica solo"),
                      ("c", "len no funciona con listas")],
                     "a", "Cambia print por return."),
        ]),
    ]))
    out.update(three(h, "u11", [
        (2, "Afianza: errores con nombre", "Una excepción interrumpe; try/except es el plan B.", [
            mc("u11-l2-e1", "`int('hola')` lanza sobre todo…",
               [("a", "ValueError"), ("b", "KeyError"), ("c", "IndentationError")],
               "a", "El tipo era int, el contenido no se puede convertir."),
            predict("u11-l2-e2", "¿Salida?", "try:\n    print(1 / 1)\nexcept ZeroDivisionError:\n    print('boom')", "1.0",
                    "No hay división por cero: el except no corre."),
            fill("u11-l2-e3", "Atrapa el error de conversión.", "try:\n    n = int(texto)\nexcept ___:\n    n = None",
                 [{"accepted": ["ValueError"]}],
                 "Atrapa el tipo concreto, no Exception a ciegas."),
            matching("u11-l2-e4", "Tipo de error.",
                     [{"id": "l1", "text": "ValueError"}, {"id": "l2", "text": "TypeError"}, {"id": "l3", "text": "KeyError"}],
                     [{"id": "r1", "text": "Contenido inválido (int('x'))"},
                      {"id": "r2", "text": "Operación entre tipos que no pegan"},
                      {"id": "r3", "text": "Clave de dict ausente"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Leer el nombre del error ya es medio arreglo."),
        ]),
        (3, "Practica: no tumbar el análisis", "Convierte sucio a número sin morir.", [
            code("u11-l3-e1",
                 "`texto = '12'`. En un try, `n = int(texto)`; si falla, `n = None`. Imprime n.",
                 "texto = '12'\n",
                 ["n == 12"],
                 "texto = '12'\ntry:\n    n = int(texto)\nexcept ValueError:\n    n = None\nprint(n)",
                 "Con '12' el try funciona. El except está por si mañana llega 'hola'.",
                 expected_stdout="12"),
            mc("u11-l3-e2", "¿Por qué es mala idea `except Exception: pass`?",
               [("a", "Te tragas bugs reales y el análisis sigue mentiroso"),
                ("b", "Python no tiene Exception"),
                ("c", "pass está prohibido")],
               "a", "Atrapa lo esperado; deja que lo inesperado se vea."),
            predict("u11-l3-e3", "¿Salida?", "try:\n    print(1 / 0)\nexcept ZeroDivisionError:\n    print('n/a')", "n/a",
                    "El plan B sustituye el crash por un mensaje o un None."),
            find_err("u11-l3-e4", "Alguien hace `raise ValueError` sin mensaje en un dato negativo. ¿Sigue siendo válido?",
                     [("a", "Sí: raise comunica que el dato no tiene sentido"),
                      ("b", "No: raise solo lo usa Python interno"),
                      ("c", "No: hay que usar print")],
                     "a", "Un error claro es mejor que un número mágico."),
        ]),
        (4, "Demuestra: limpieza defensiva", "Decide qué hacer con un valor podrido.", [
            code("u11-l4-e1",
                 "`bruto = ['3', 'x', '5']`. Crea `limpios` con los int que se puedan. Imprime limpios.",
                 "bruto = ['3', 'x', '5']\n",
                 ["limpios == [3, 5]"],
                 "bruto = ['3', 'x', '5']\nlimpios = []\nfor t in bruto:\n    try:\n        limpios.append(int(t))\n    except ValueError:\n        pass\nprint(limpios)",
                 "En Pandas será to_numeric(..., errors='coerce'). Aquí ves el mecanismo.",
                 expected_stdout="[3, 5]"),
            matching("u11-l4-e2", "Estrategia.",
                     [{"id": "l1", "text": "Coerce a NaN"}, {"id": "l2", "text": "Rechazar la fila"}, {"id": "l3", "text": "Parar"}],
                     [{"id": "r1", "text": "Dejas hueco y sigues"},
                      {"id": "r2", "text": "Esa observación no entra al modelo"},
                      {"id": "r3", "text": "El archivo está irreconocible"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "No hay una sola respuesta: documenta la que elijas."),
            mc("u11-l4-e3", "Un CSV de 1 millón de filas con 3 'N/A'. ¿Qué suele ser razonable?",
               [("a", "Convertir esos 3 a nulo y seguir, midiendo cuántos se cayeron"),
                ("b", "Borrar el archivo entero"),
                ("c", "Ignorar el tipo y sumar strings")],
               "a", "Cuenta los nulos. Si son el 40%, ya no es '3 celdas'."),
            predict("u11-l4-e4", "¿Salida?", "print(isinstance('3', str))", "True",
                    "Antes de int(), a veces preguntas el tipo. En tablas, el dtype lo dice Pandas."),
        ]),
    ]))
    out.update(three(h, "u12", [
        (2, "Afianza: molde y ejemplar", "La clase es el plano; el objeto, un ejemplar con self.", [
            mc("u12-l2-e1", "`self` dentro de un método es…",
               [("a", "Este objeto concreto"), ("b", "La clase entera"), ("c", "Un módulo")],
               "a", "No lo pasas al llamar: Python pone c.tick() → tick(c)."),
            predict("u12-l2-e2", "¿Salida?",
                    "class C:\n    def __init__(self):\n        self.n = 2\nprint(C().n)", "2",
                    "__init__ corre al hacer C() y guarda n en ese objeto."),
            fill("u12-l2-e3", "Crea un objeto.", "c = Contador___", [{"accepted": ["()"]}],
                 "Los paréntesis llaman a la clase: fabrican una instancia."),
            matching("u12-l2-e4", "Palabra OOP.",
                     [{"id": "l1", "text": "Clase"}, {"id": "l2", "text": "Instancia"}, {"id": "l3", "text": "Método"}],
                     [{"id": "r1", "text": "El plano"}, {"id": "r2", "text": "Un objeto real"},
                      {"id": "r3", "text": "Función pegada al objeto"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     ".fit() de un modelo es un método: el estado queda en el objeto."),
        ]),
        (3, "Practica: un contador", "Guarda estado y expón una acción.", [
            code("u12-l3-e1",
                 "Clase `Caja` con `__init__` que pone `self.n = 0` y `inc` que suma 1. Crea c, llama inc, imprime c.n.",
                 "",
                 ["c.n == 1"],
                 "class Caja:\n    def __init__(self):\n        self.n = 0\n    def inc(self):\n        self.n += 1\nc = Caja()\nc.inc()\nprint(c.n)",
                 "El estado vive en self.n, no en una variable global.",
                 expected_stdout="1"),
            mc("u12-l3-e2", "Dos objetos `a = Caja(); b = Caja()`. ¿Comparten n?",
               [("a", "No: cada uno tiene su self.n"),
                ("b", "Sí: hay un único n del programa"),
                ("c", "Solo si los nombres coinciden")],
               "a", "Por eso puedes tener dos modelos entrenados distintos."),
            find_err("u12-l3-e3", "Un método usa `n += 1` sin self. ¿Qué suele pasar?",
                     [("a", "UnboundLocalError o no toca el atributo del objeto"),
                      ("b", "Python crea self solo"),
                      ("c", "Siempre funciona")],
                     "a", "El estado del objeto es self.n."),
            predict("u12-l3-e4", "¿Salida?",
                    "class P:\n    def __init__(self, x):\n        self.x = x\nprint(P(9).x)", "9",
                    "Los argumentos de __init__ después de self son los que pasas a P(9)."),
        ]),
        (4, "Demuestra: por qué .fit existe", "El objeto recuerda lo aprendido.", [
            mc("u12-l4-e1", "En scikit-learn, `modelo.fit(X, y)` guarda…",
               [("a", "Parámetros aprendidos dentro del objeto modelo"),
                ("b", "Un CSV en disco siempre"),
                ("c", "Nada: fit es solo un alias de print")],
               "a", "Por eso luego `modelo.predict(X2)` usa ese estado."),
            code("u12-l4-e2",
                 "Clase `Media` con `fit(self, xs)` que guarda `self.m = sum(xs)/len(xs)` y `predict` que devuelve self.m. "
                 "Ajusta con [2, 4], imprime predict().",
                 "",
                 ["abs(est.m - 3) < 1e-9"],
                 "class Media:\n    def fit(self, xs):\n        self.m = sum(xs) / len(xs)\n    def predict(self):\n        return self.m\nest = Media()\nest.fit([2, 4])\nprint(est.predict())",
                 "Es un modelo ridículo (siempre la media) y por eso se entiende fit/predict.",
                 expected_stdout="3.0"),
            matching("u12-l4-e3", "API de estimador.",
                     [{"id": "l1", "text": "fit"}, {"id": "l2", "text": "predict"}, {"id": "l3", "text": "atributos_"}],
                     [{"id": "r1", "text": "Aprende de X, y"},
                      {"id": "r2", "text": "Aplica lo aprendido a datos nuevos"},
                      {"id": "r3", "text": "Estado interno (coef_, mean_)"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "El guion bajo final es convención: 'esto se llenó en fit'."),
            find_err("u12-l4-e4", "Llamar `predict` antes de `fit`. ¿El fallo conceptual?",
                     [("a", "El objeto aún no tiene parámetros aprendidos"),
                      ("b", "predict no existe en Python"),
                      ("c", "Hay que importar self")],
                     "a", "NotFittedError en sklearn. Aquí: AttributeError si no creaste self.m."),
        ]),
    ]))
    out.update(three(h, "u13", [
        (2, "Afianza: traer código ajeno", "import carga un módulo; as le pone mote.", [
            mc("u13-l2-e1", "`import numpy as np` significa…",
               [("a", "Cargas NumPy y lo llamas np"),
                ("b", "Instalas NumPy con pip"),
                ("c", "Renombras tu archivo a numpy")],
               "a", "as no cambia la librería, solo el nombre corto."),
            predict("u13-l2-e2", "¿Salida?", "import math\nprint(int(math.sqrt(9)))", "3",
                    "math.sqrt(9) es 3.0; int lo deja en 3."),
            fill("u13-l2-e3", "Alias de pandas.", "import pandas ___ pd", [{"accepted": ["as"]}],
                 "pd es la convención, igual que np."),
            matching("u13-l2-e4", "Forma de importar.",
                     [{"id": "l1", "text": "import math"}, {"id": "l2", "text": "from math import sqrt"},
                      {"id": "l3", "text": "from math import *"}],
                     [{"id": "r1", "text": "Usas math.sqrt"},
                      {"id": "r2", "text": "Usas sqrt directo"},
                      {"id": "r3", "text": "Ensucia el espacio de nombres: evítalo"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "En datos, import numpy as np es el hábito sano."),
        ]),
        (3, "Practica: usar lo importado", "Llama una función de math o statistics.", [
            code("u13-l3-e1",
                 "Importa math y guarda `r = math.sqrt(16)`. Imprime int(r).",
                 "",
                 ["r == 4"],
                 "import math\nr = math.sqrt(16)\nprint(int(r))",
                 "El prefijo math. deja claro de dónde sale sqrt.",
                 expected_stdout="4"),
            mc("u13-l3-e2", "En PyQuest (navegador), pip…",
               [("a", "No hace falta para NumPy/Pandas/Matplotlib: ya vienen en Pyodide"),
                ("b", "Hay que ejecutarlo en cada ejercicio"),
                ("c", "Sustituye a import")],
               "a", "pip es para tu ordenador. Aquí el runtime ya trae el stack de datos."),
            find_err("u13-l3-e3", "`import panda as pd` (sin s). ¿Qué pasa?",
                     [("a", "ModuleNotFoundError: el módulo se llama pandas"),
                      ("b", "Python corrige el typo"),
                      ("c", "Carga NumPy")],
                     "a", "El nombre del paquete es parte de la API."),
            predict("u13-l3-e4", "¿Salida?", "from math import pi\nprint(int(pi))", "3",
                    "from import trae el nombre suelto. int(pi) trunca a 3."),
        ]),
        (4, "Demuestra: el stack de datos", "Sabes qué librería hace qué.", [
            matching("u13-l4-e1", "Librería y trabajo.",
                     [{"id": "l1", "text": "NumPy"}, {"id": "l2", "text": "Pandas"}, {"id": "l3", "text": "Matplotlib"}],
                     [{"id": "r1", "text": "Arrays numéricos"},
                      {"id": "r2", "text": "Tablas (DataFrame)"},
                      {"id": "r3", "text": "Gráficos"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "sklearn y seaborn se apoyan en este trío."),
            mc("u13-l4-e2", "¿Por qué no haces `from numpy import *` en un notebook serio?",
               [("a", "No sabes si mean es de NumPy, de statistics o tuya"),
                ("b", "Es más lento siempre x1000"),
                ("c", "NumPy lo prohíbe")],
               "a", "np.mean se lee y se busca."),
            code("u13-l4-e3",
                 "import numpy as np; `a = np.array([1, 2, 3])`; imprime `int(a.sum())`.",
                 "",
                 ["int(a.sum()) == 6"],
                 "import numpy as np\na = np.array([1, 2, 3])\nprint(int(a.sum()))",
                 "Este es el primer gesto NumPy: array + operación de todos.",
                 expected_stdout="6"),
            find_err("u13-l4-e4", "Mezclar `import math` y luego `np.sqrt` sin importar numpy. ¿Fallo?",
                     [("a", "np no existe hasta `import numpy as np`"),
                      ("b", "math.sqrt borra np"),
                      ("c", "sqrt está prohibido")],
                     "a", "Cada mote se crea con su import."),
        ]),
    ]))
    out.update(_project(h, "p0", "stats de bolsillo", "media",
                        "xs = [2, 4, 6]\nmedia = sum(xs) / len(xs)\nprint(media)",
                        ["abs(media - 4) < 1e-9"], "4.0",
                        "La media de 2, 4 y 6 es 4. Un proyecto es función + un número que puedes defender."))
    out.update(three(h, "u14", [
        (2, "Afianza: muchos números, un bloque", "El array es homogéneo y tiene shape.", [
            mc("u14-l2-e1", "¿Por qué NumPy y no una lista para 100 000 temperaturas?",
               [("a", "Opera todos los números a la vez, en un bloque compacto"),
                ("b", "Las listas no pueden guardar floats"),
                ("c", "NumPy imprime más bonito")],
               "a", "El for de Python es el cuello de botella. El array lo evita."),
            predict("u14-l2-e2", "¿Salida?", "import numpy as np\nprint(np.array([1, 2, 3]) * 2)", "[2 4 6]",
                    "Multiplica cada celda. Sin for."),
            fill("u14-l2-e3", "Convierte la lista.", "a = np.___([1, 2, 3])", [{"accepted": ["array"]}],
                 "np.array es la puerta de entrada."),
            matching("u14-l2-e4", "Atributo.",
                     [{"id": "l1", "text": "shape"}, {"id": "l2", "text": "dtype"}, {"id": "l3", "text": "ndim"}],
                     [{"id": "r1", "text": "Tamaño en cada eje"},
                      {"id": "r2", "text": "Tipo de cada celda"},
                      {"id": "r3", "text": "Cuántas dimensiones"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "(3,) es una fila de 3. (2, 3) es tabla 2×3."),
        ]),
        (3, "Practica: crear y medir", "array, arange, shape.", [
            code("u14-l3-e1",
                 "import numpy as np. `a = np.arange(4)`. Imprime `a.shape[0]`.",
                 "import numpy as np\n",
                 ["a.shape == (4,)"],
                 "import numpy as np\na = np.arange(4)\nprint(a.shape[0])",
                 "arange(4) es 0,1,2,3. shape (4,) tiene 4 celdas.",
                 expected_stdout="4"),
            mc("u14-l3-e2", "Si metes un 1.5 en un array de enteros, NumPy suele…",
               [("a", "Subir el dtype a float para que quepan todos"),
                ("b", "Borrar el 1.5"),
                ("c", "Convertir todo a string")],
               "a", "Homogéneo: un decimal contagia el tipo."),
            predict("u14-l3-e3", "¿Salida?", "import numpy as np\nprint(np.zeros(2))", "[0. 0.]",
                    "zeros crea floats 0.0 por defecto."),
            find_err("u14-l3-e4", "`np.array([1, 2]) + [3]`. ¿Qué idea de broadcasting hay aquí?",
                     [("a", "El [3] se estira y suma 3 a cada celda → [4, 5]"),
                      ("b", "Siempre explota"),
                      ("c", "Concatena en una lista Python")],
                     "a", "1-D + escalar/vector compatible es el truco del broadcasting."),
        ]),
        (4, "Demuestra: pensar en bloques", "Olvida el índice i salvo que haga falta.", [
            code("u14-l4-e1",
                 "`t = np.array([10., 20., 30.])`. `c = (t - 10) / 10`. Imprime `c[0]`.",
                 "import numpy as np\nt = np.array([10., 20., 30.])\n",
                 ["abs(float(c[0])) < 1e-9", "abs(float(c[1]) - 1) < 1e-9"],
                 "import numpy as np\nt = np.array([10., 20., 30.])\nc = (t - 10) / 10\nprint(c[0])",
                 "Normalizar toda la serie de un golpe: resta y divide el array entero.",
                 expected_stdout="0.0"),
            mc("u14-l4-e2", "`a.mean()` sin axis…",
               [("a", "Resume todo el array a un número"),
                ("b", "Devuelve una fila"),
                ("c", "Borra a")],
               "a", "axis=0/1 elige dirección cuando hay 2D."),
            matching("u14-l4-e3", "Creación.",
                     [{"id": "l1", "text": "np.array([...])"}, {"id": "l2", "text": "np.arange(n)"}, {"id": "l3", "text": "np.ones((2, 3))"}],
                     [{"id": "r1", "text": "Desde una lista"},
                      {"id": "r2", "text": "0..n-1"},
                      {"id": "r3", "text": "Tabla 2×3 de unos"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "ones/zeros/full construyen el lienzo; array convierte lo que ya tienes."),
            predict("u14-l4-e4", "¿Salida?", "import numpy as np\nprint(np.array([1, 2]).sum())", "3",
                    "sum en el array suma celdas, no concatena como en strings."),
        ]),
    ]))
    out.update(three(h, "u15", [
        (2, "Afianza: señalar celdas", "Un índice, un slice, o una máscara True/False.", [
            mc("u15-l2-e1", "En 2D, `m[0, 1]` es…",
               [("a", "Fila 0, columna 1"), ("b", "Fila 1, columna 0"), ("c", "Un slice de toda la fila 0")],
               "a", "Primero fila, luego columna. Empiezan en 0."),
            predict("u15-l2-e2", "¿Salida?",
                    "import numpy as np\na = np.array([10, 20, 30, 40])\nprint(a[1:3])", "[20 30]",
                    "[1:3] incluye 1 y excluye 3."),
            fill("u15-l2-e3", "Último elemento.", "print(a[___])", [{"accepted": ["-1"]}],
                 "El -1 cuenta desde el final, igual que en listas."),
            matching("u15-l2-e4", "Selección.",
                     [{"id": "l1", "text": "a[0]"}, {"id": "l2", "text": "a[:2]"}, {"id": "l3", "text": "a[a > 0]"}],
                     [{"id": "r1", "text": "Una celda"},
                      {"id": "r2", "text": "Un trozo contiguo"},
                      {"id": "r3", "text": "Filtro por condición"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "La máscara es el gesto de analista: qué filas cumplen."),
        ]),
        (3, "Practica: máscaras", "Filtra con una comparación.", [
            code("u15-l3-e1",
                 "`a = np.array([1, 5, 9])`. `altos = a[a >= 5]`. Imprime `altos.sum()`.",
                 "import numpy as np\na = np.array([1, 5, 9])\n",
                 ["int(altos.sum()) == 14"],
                 "import numpy as np\na = np.array([1, 5, 9])\naltos = a[a >= 5]\nprint(int(altos.sum()))",
                 "a >= 5 es [False, True, True]; indexar con eso deja 5 y 9.",
                 expected_stdout="14"),
            mc("u15-l3-e2", "Un slice de NumPy suele ser…",
               [("a", "Una vista: cambiar el trozo puede cambiar el original"),
                ("b", "Siempre una copia profunda"),
                ("c", "Un string")],
               "a", "Si necesitas independencia, .copy()."),
            predict("u15-l3-e3", "¿Salida?",
                    "import numpy as np\nm = np.array([[1, 2], [3, 4]])\nprint(m[:, 0])", "[1 3]",
                    ": es 'todas las filas'. Columna 0."),
            find_err("u15-l3-e4", "`a[a > 3 and a < 8]` con arrays. ¿Por qué explota?",
                     [("a", "and de Python no combina arrays; usa & y paréntesis"),
                      ("b", "No se puede filtrar dos veces"),
                      ("c", "Hay que usar or")],
                     "a", "(a > 3) & (a < 8). Los paréntesis son obligatorios."),
        ]),
        (4, "Demuestra: cortar con intención", "El filtro es una hipótesis: nómbrala.", [
            code("u15-l4-e1",
                 "`s = np.array([0., 1., 0., 4.])`. `n_pos = int((s > 0).sum())`. Imprime n_pos.",
                 "import numpy as np\ns = np.array([0., 1., 0., 4.])\n",
                 ["n_pos == 2"],
                 "import numpy as np\ns = np.array([0., 1., 0., 4.])\nn_pos = int((s > 0).sum())\nprint(n_pos)",
                 "True cuenta como 1. Sumar la máscara es contar cuántos cumplen.",
                 expected_stdout="2"),
            mc("u15-l4-e2", "`m[:, 1]` se lee…",
               [("a", "Todas las filas, solo la columna 1"),
                ("b", "Todas las columnas, fila 1"),
                ("c", "La celda 1,1")],
               "a", "El primer hueco es filas. El segundo, columnas."),
            matching("u15-l4-e3", "Peligro.",
                     [{"id": "l1", "text": "Vista vs copia"}, {"id": "l2", "text": "Índice negativo"}, {"id": "l3", "text": "Máscara vacía"}],
                     [{"id": "r1", "text": "Mutar un trozo muta la fuente"},
                      {"id": "r2", "text": "a[-1] es el último, no un error"},
                      {"id": "r3", "text": "mean de [] no existe: comprueba len"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Antes de un resumen, mira si el filtro dejó algo."),
            predict("u15-l4-e4", "¿Salida?",
                    "import numpy as np\na = np.arange(5)\nprint(a[[0, 4]])", "[0 4]",
                    "Una lista de enteros es fancy indexing: celdas sueltas, no un rango."),
        ]),
    ]))
    out.update(three(h, "u16", [
        (2, "Afianza: sin for celda a celda", "Vectorizar = una operación para todo el array.", [
            mc("u16-l2-e1", "Una ufunc como np.sqrt…",
               [("a", "Se aplica a cada celda, en código rápido"),
                ("b", "Solo funciona con un float suelto"),
                ("c", "Borra los negativos siempre")],
               "a", "Si escribiste for i in range(len(x)), hay ufunc."),
            predict("u16-l2-e2", "¿Salida?", "import numpy as np\nprint(np.sqrt(np.array([1., 4., 9.])))", "[1. 2. 3.]",
                    "Tres raíces en una llamada."),
            fill("u16-l2-e3", "Dónde sí, dónde no.", "y = np.___(x, 0)  # recorta negativos a 0", [{"accepted": ["clip", "maximum"]}],
                 "clip(x, 0, None) o maximum(x, 0) evitan el for del 'si es negativo, 0'."),
            matching("u16-l2-e4", "Idea.",
                     [{"id": "l1", "text": "Vectorizar"}, {"id": "l2", "text": "Broadcasting"}, {"id": "l3", "text": "for Python"}],
                     [{"id": "r1", "text": "La misma cuenta a todo el bloque"},
                      {"id": "r2", "text": "Estirar un vector para que encaje con una tabla"},
                      {"id": "r3", "text": "Útil para lógica rara; lento en millones de celdas"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Broadcasting no copia de más: alinea formas."),
        ]),
        (3, "Practica: where y cuentas", "np.where es el if vectorizado.", [
            code("u16-l3-e1",
                 "`x = np.array([1, 8, 3])`. `y = np.where(x > 5, 1, 0)`. Imprime `int(y.sum())`.",
                 "import numpy as np\nx = np.array([1, 8, 3])\n",
                 ["int(y.sum()) == 1"],
                 "import numpy as np\nx = np.array([1, 8, 3])\ny = np.where(x > 5, 1, 0)\nprint(int(y.sum()))",
                 "where(cond, si_true, si_false). Solo 8 pasa el umbral.",
                 expected_stdout="1"),
            mc("u16-l3-e2", "`x + 1` con x array…",
               [("a", "Suma 1 a cada celda (broadcast del escalar)"),
                ("b", "Añade un elemento 1 al final"),
                ("c", "Convierte x en lista")],
               "a", "El escalar se estira mentalmente al shape de x."),
            predict("u16-l3-e3", "¿Salida aproximada del print?",
                    "import numpy as np\nprint(np.array([0, 10]).mean())", "5.0",
                    "mean vectorizada: no sumes a mano."),
            find_err("u16-l3-e4", "Sumar (2, 3) con (3,) que no alinea. ¿Qué exiges?",
                     [("a", "Que las formas sean compatibles a la derecha, o reshapes"),
                      ("b", "Que ambos sean listas Python"),
                      ("c", "Un for anidado obligatorio")],
                     "a", "ValueError: operands could not be broadcast. Dibuja los shapes."),
        ]),
        (4, "Demuestra: reescribe el for", "Traduce un bucle a una línea NumPy.", [
            code("u16-l4-e1",
                 "`x = np.array([0., 5., 10.])`. `z = (x - x.mean())`. Imprime `round(float(z.mean()), 5)`.",
                 "import numpy as np\nx = np.array([0., 5., 10.])\n",
                 ["abs(float(z.mean())) < 1e-9"],
                 "import numpy as np\nx = np.array([0., 5., 10.])\nz = x - x.mean()\nprint(round(float(z.mean()), 5))",
                 "Centrar: restar la media. El nuevo promedio es ~0.",
                 expected_stdout="0.0"),
            matching("u16-l4-e2", "Traducción.",
                     [{"id": "l1", "text": "if x>0: 1 else 0"}, {"id": "l2", "text": "min(max(x,0),1)"}, {"id": "l3", "text": "x ** 2"}],
                     [{"id": "r1", "text": "np.where(x>0, 1, 0)"},
                      {"id": "r2", "text": "np.clip(x, 0, 1)"},
                      {"id": "r3", "text": "x ** 2  (ya vectorizado)"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "El ** sobre arrays también es ufunc."),
            mc("u16-l4-e3", "¿Cuándo sí dejas un for?",
               [("a", "Cuando cada vuelta depende de la anterior de forma irregular"),
                ("b", "Siempre que haya más de 3 números"),
                ("c", "Nunca, ni para leer un archivo")],
               "a", "Recurrencias raras, I/O, o lógica de negocio muy ramificada."),
            predict("u16-l4-e4", "¿Salida?", "import numpy as np\nprint(np.array([1, 2, 3]).prod())", "6",
                    "prod multiplica celdas: 1*2*3."),
        ]),
    ]))
    out.update(three(h, "u17", [
        (2, "Afianza: un número que resume muchos", "Media, mediana, std; axis elige la dirección.", [
            mc("u17-l2-e1", "La mediana aguanta mejor que la media un 999 colado porque…",
               [("a", "Es el valor del centro al ordenar, no un promedio arrastrado"),
                ("b", "Ignora todos los datos"),
                ("c", "Siempre vale 0")],
               "a", "Un outlier tira de la media. La mediana apenas se mueve."),
            predict("u17-l2-e2", "¿Salida?", "import numpy as np\nprint(np.median([1, 2, 100]))", "2.0",
                    "Ordenados 1,2,100: el centro es 2."),
            fill("u17-l2-e3", "Media de todo el array.", "print(x.___())", [{"accepted": ["mean"]}],
                 "sin axis resume todas las celdas."),
            matching("u17-l2-e4", "axis en 2D.",
                     [{"id": "l1", "text": "axis=0"}, {"id": "l2", "text": "axis=1"}, {"id": "l3", "text": "sin axis"}],
                     [{"id": "r1", "text": "Baja por filas: un número por columna"},
                      {"id": "r2", "text": "A lo ancho: un número por fila"},
                      {"id": "r3", "text": "Un solo número de toda la tabla"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Dibuja la tabla. Pregunta: ¿resumen por columna o por fila?"),
        ]),
        (3, "Practica: mean y std", "Calcula y redondea para comunicar.", [
            code("u17-l3-e1",
                 "`x = np.array([2., 4., 6.])`. Imprime `int(x.mean())`.",
                 "import numpy as np\nx = np.array([2., 4., 6.])\n",
                 ["abs(float(x.mean()) - 4) < 1e-9"],
                 "import numpy as np\nx = np.array([2., 4., 6.])\nprint(int(x.mean()))",
                 "2+4+6=12, entre 3 es 4.",
                 expected_stdout="4"),
            mc("u17-l3-e2", "En NumPy, std por defecto divide por n (no n-1). Eso importa cuando…",
               [("a", "Comparas con la std muestral de un libro de estadística"),
                ("b", "Nunca: da igual"),
                ("c", "Solo en strings")],
               "a", "ddof=1 pide la versión muestral."),
            predict("u17-l3-e3", "¿Salida?",
                    "import numpy as np\nprint(np.array([[1, 3], [5, 7]]).mean(axis=0))", "[3. 5.]",
                    "Columnas: (1+5)/2=3, (3+7)/2=5."),
            find_err("u17-l3-e4", "Hacer mean de un array de NaN sin nanmean. ¿Qué pasa?",
                     [("a", "El resultado se contagia a NaN"),
                      ("b", "Python borra NaN solo"),
                      ("c", "Da 0")],
                     "a", "np.nanmean ignora NaNs. Primero decide si el nulo es válido."),
        ]),
        (4, "Demuestra: el resumen es una afirmación", "Elige métrica según el relato.", [
            mc("u17-l4-e1", "Sueldos con un CEO millonario. ¿Qué centro cuentas en un titular honesto?",
               [("a", "Mediana, y mencionas la media si hace falta"),
                ("b", "Solo el máximo"),
                ("c", "La std")],
               "a", "La métrica es parte del mensaje. Elígelo, no lo escondas."),
            code("u17-l4-e2",
                 "`x = np.array([1., 1., 1., 10.])`. `m, med = x.mean(), np.median(x)`. Imprime int(med).",
                 "import numpy as np\nx = np.array([1., 1., 1., 10.])\n",
                 ["abs(float(np.median(x)) - 1) < 1e-9"],
                 "import numpy as np\nx = np.array([1., 1., 1., 10.])\nm, med = x.mean(), np.median(x)\nprint(int(med))",
                 "Media ~3.25, mediana 1. El 10 tira del promedio.",
                 expected_stdout="1"),
            matching("u17-l4-e3", "Métrica.",
                     [{"id": "l1", "text": "mean"}, {"id": "l2", "text": "median"}, {"id": "l3", "text": "std"}],
                     [{"id": "r1", "text": "Centro aritmético"},
                      {"id": "r2", "text": "Centro robusto"},
                      {"id": "r3", "text": "Dispersión"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Un std alto con media baja: hay cola o outliers."),
            predict("u17-l4-e4", "¿Salida?", "import numpy as np\nprint(np.percentile([0, 10, 20], 50))", "10.0",
                    "Percentil 50 = mediana."),
        ]),
    ]))
    out.update(three(h, "u18", [
        (2, "Afianza: misma plastilina, otro molde", "reshape no inventa celdas; el producto debe cuadrar.", [
            mc("u18-l2-e1", "`np.arange(6).reshape(2, 3)` es…",
               [("a", "Los 6 números en 2 filas × 3 columnas"),
                ("b", "12 números nuevos"),
                ("c", "Una lista de listas Python")],
               "a", "0..5 recortados en 2×3."),
            predict("u18-l2-e2", "¿Salida de shape?",
                    "import numpy as np\nprint(np.arange(6).reshape(3, 2).shape)", "(3, 2)",
                    "3 filas, 2 columnas. Siguen siendo 6 celdas."),
            fill("u18-l2-e3", "Deja que calcule un lado.", "a.reshape(2, ___)", [{"accepted": ["-1"]}],
                 "-1 significa 'tú pon el número que cuadre'."),
            matching("u18-l2-e4", "Herramienta.",
                     [{"id": "l1", "text": "reshape"}, {"id": "l2", "text": "ravel"}, {"id": "l3", "text": "clip"}],
                     [{"id": "r1", "text": "Cambia filas/columnas"},
                      {"id": "r2", "text": "Pasa a 1D"},
                      {"id": "r3", "text": "Recorta valores a un rango"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "ravel/flatten son el 'deshacer la tabla'."),
        ]),
        (3, "Practica: where como filtro de valores", "Cambia celdas que no cumplen.", [
            code("u18-l3-e1",
                 "`a = np.arange(4)`. `b = np.where(a > 1, a, 0)`. Imprime `int(b.sum())`.",
                 "import numpy as np\na = np.arange(4)\n",
                 ["int(b.sum()) == 5"],
                 "import numpy as np\na = np.arange(4)\nb = np.where(a > 1, a, 0)\nprint(int(b.sum()))",
                 "a es 0,1,2,3. where deja 0,0,2,3. Suma 5.",
                 expected_stdout="5"),
            mc("u18-l3-e2", "reshape(2, 5) sobre 6 celdas…",
               [("a", "Error: 2×5=10 ≠ 6"),
                ("b", "Rellena con ceros"),
                ("c", "Recorta a 6")],
               "a", "El recorte tiene que usar exactamente las celdas que hay."),
            predict("u18-l3-e3", "¿Salida?", "import numpy as np\nprint(np.clip([-1, 0.5, 8], 0, 1))", "[0.  0.5 1. ]",
                    "Por debajo de 0 → 0. Por encima de 1 → 1."),
            find_err("u18-l3-e4", "Confundir reshape con transpuesta. ¿La diferencia?",
                     [("a", "reshape reordena en memoria/forma; T intercambia ejes 0 y 1"),
                      ("b", "Son sinónimos"),
                      ("c", "T borra datos")],
                     "a", "[[1,2,3],[4,5,6]].T es 3×2 distinto de reshape(3,2) según el orden."),
        ]),
        (4, "Demuestra: preparar X para un modelo", "Aplanar imágenes o recortar outliers.", [
            mc("u18-l4-e1", "Una imagen 8×8 a un vector de 64 para un modelo lineal. ¿Qué usas?",
               [("a", "reshape(64,) o ravel"),
                ("b", "clip a 8"),
                ("c", "mean axis=0")],
               "a", "MNIST aplana 28×28 a 784. Es reshape, no magia."),
            code("u18-l4-e2",
                 "`a = np.arange(6).reshape(2, 3)`. `v = a.ravel()`. Imprime `v.shape[0]`.",
                 "import numpy as np\na = np.arange(6).reshape(2, 3)\n",
                 ["v.shape == (6,)"],
                 "import numpy as np\na = np.arange(6).reshape(2, 3)\nv = a.ravel()\nprint(v.shape[0])",
                 "De tabla a fila: el modelo lineal ve un vector.",
                 expected_stdout="6"),
            matching("u18-l4-e3", "Limpieza numérica.",
                     [{"id": "l1", "text": "clip salarios a un tope"}, {"id": "l2", "text": "where edad < 0 → NaN"},
                      {"id": "l3", "text": "reshape a (n, 1)"}],
                     [{"id": "r1", "text": "Outliers extremos"},
                      {"id": "r2", "text": "Valores imposibles"},
                      {"id": "r3", "text": "sklearn espera 2D en X"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "reshape(-1, 1) es el truco para una sola feature."),
            predict("u18-l4-e4", "¿Salida?",
                    "import numpy as np\nprint(np.arange(4).reshape(-1, 1).shape)", "(4, 1)",
                    "-1 calcula 4 filas. 1 columna. Listo para fit."),
        ]),
    ]))
    out.update(_project(h, "p1", "temperaturas", "media",
                        "import numpy as np\nt = np.array([12.0, 18.0, 15.0])\nmedia = float(t.mean())\nprint(round(media, 1))",
                        ["abs(media - 15) < 1e-9"], "15.0",
                        "Tres lecturas, una media. Mira si hay un 999 antes de creerte el número."))
    out.update(three(h, "u19", [
        (2, "Afianza: lienzo y ejes", "Figure es la imagen; Axes es el recuadro X/Y.", [
            mc("u19-l2-e1", "`fig, ax = plt.subplots()` te da…",
               [("a", "El lienzo y un eje donde pintar"),
                ("b", "Un DataFrame"),
                ("c", "Un modelo entrenado")],
               "a", "ax.plot, ax.set_title: casi todo pasa por el Axes."),
            matching("u19-l2-e2", "Tipo de gráfico.",
                     [{"id": "l1", "text": "Línea"}, {"id": "l2", "text": "Barras"}, {"id": "l3", "text": "Histograma"}],
                     [{"id": "r1", "text": "Evolución en el tiempo"},
                      {"id": "r2", "text": "Comparar categorías"},
                      {"id": "r3", "text": "Cómo se reparte una variable"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Scatter es dos medidas a la vez: cada punto una fila."),
            fill("u19-l2-e3", "Pinta una serie.", "ax.___(x, y)", [{"accepted": ["plot"]}],
                 "plot es la línea. bar, hist, scatter son primas."),
            find_err("u19-l2-e4", "Un gráfico sin etiqueta en Y. ¿El problema de comunicación?",
                     [("a", "No se sabe qué se mide ni en qué unidades"),
                      ("b", "Matplotlib no dibuja"),
                      ("c", "Hay que usar 3D")],
                     "a", "set_ylabel no es adorno."),
        ]),
        (3, "Practica: un plot mínimo", "Título y un dato que se pueda leer.", [
            code("u19-l3-e1",
                 "import matplotlib.pyplot as plt. Crea fig, ax. `ys = [1, 3, 2]`. ax.plot(ys). Guarda `n = len(ys)` e imprime n.",
                 "import matplotlib.pyplot as plt\n",
                 ["n == 3"],
                 "import matplotlib.pyplot as plt\nfig, ax = plt.subplots()\nys = [1, 3, 2]\nax.plot(ys)\nn = len(ys)\nprint(n)",
                 "El gráfico existe aunque el test mire el dato. En PyQuest verás la figura si capturePlots.",
                 expected_stdout="3",
                 capture_plots=True),
            mc("u19-l3-e2", "Un histograma responde…",
               [("a", "¿Hay muchos valores bajos y pocos altos, o al revés?"),
                ("b", "¿Quién ganó el mes?"),
                ("c", "¿Cuál es la correlación exacta?")],
               "a", "Forma de una sola variable. No sustituye a un scatter."),
            predict("u19-l3-e3", "¿Cuántos puntos pinta scatter de x=[1,2], y=[3,4]?",
                    "print(2)", "2",
                    "Un punto por posición i: (1,3) y (2,4)."),
            matching("u19-l3-e4", "Método.",
                     [{"id": "l1", "text": "set_title"}, {"id": "l2", "text": "set_xlabel"}, {"id": "l3", "text": "legend"}],
                     [{"id": "r1", "text": "Qué demuestra el gráfico"},
                      {"id": "r2", "text": "Qué es el eje X"},
                      {"id": "r3", "text": "Qué color es qué serie"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Si hay dos líneas, la leyenda no es opcional."),
        ]),
        (4, "Demuestra: elige el gráfico", "La forma sigue a la pregunta.", [
            mc("u19-l4-e1", "Comparar ventas de 4 productos este mes. ¿Cuál?",
               [("a", "Barras"), ("b", "Histograma de un producto"), ("c", "Línea de un único punto")],
               "a", "Categoría vs número: barras. Ordena por valor, no por alfabeto."),
            matching("u19-l4-e2", "Pregunta → gráfico.",
                     [{"id": "l1", "text": "¿Cómo evoluciona?"}, {"id": "l2", "text": "¿X e Y se mueven juntas?"},
                      {"id": "l3", "text": "¿Cuál es la forma de X?"}],
                     [{"id": "r1", "text": "Línea"}, {"id": "r2", "text": "Scatter"}, {"id": "r3", "text": "Histograma"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Si no puedes decir la pregunta, no dibujes."),
            find_err("u19-l4-e3", "Un pastel con 30 categorías. ¿Por qué suele ser mala idea?",
                     [("a", "El ojo no compara ángulos entre tantas rebanadas"),
                      ("b", "Matplotlib no pinta pies"),
                      ("c", "Hay que usar 4 pies")],
                     "a", "Barras horizontales. El pastel aguanta 2-4 partes."),
            code("u19-l4-e4",
                 "`cats = ['A', 'B']`; `vals = [10, 30]`. `ganador = cats[vals.index(max(vals))]`. Imprime ganador.",
                 "cats = ['A', 'B']\nvals = [10, 30]\n",
                 ["ganador == 'B'"],
                 "cats = ['A', 'B']\nvals = [10, 30]\nganador = cats[vals.index(max(vals))]\nprint(ganador)",
                 "Antes de dibujar, ya sabes el mensaje: B duplica a A.",
                 expected_stdout="B"),
        ]),
    ]))
    out.update(three(h, "u20", [
        (2, "Afianza: el eje también habla", "Límites, leyenda y unidades no son decoración.", [
            mc("u20-l2-e1", "Zoomar el eje Y para que una subida de 0.1 se vea enorme…",
               [("a", "Puede ser engañoso si no lo dices"),
                ("b", "Es obligatorio en ciencia"),
                ("c", "Matplotlib lo prohíbe")],
               "a", "set_ylim es una decisión. Documenta el recorte."),
            matching("u20-l2-e2", "Control.",
                     [{"id": "l1", "text": "set_xlim/ylim"}, {"id": "l2", "text": "grid"}, {"id": "l3", "text": "tight_layout"}],
                     [{"id": "r1", "text": "Qué rango se ve"},
                      {"id": "r2", "text": "Guías para leer valores"},
                      {"id": "r3", "text": "Evita títulos cortados"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Un título cortado no se puede citar."),
            fill("u20-l2-e3", "Nombra el eje Y.", "ax.___('USD')", [{"accepted": ["set_ylabel"]}],
                 "set_ylabel. Las unidades van ahí, no solo en el título."),
            find_err("u20-l2-e4", "Dos series del mismo color sin leyenda. ¿Qué falla?",
                     [("a", "No se distingue qué es qué"),
                      ("b", "Python mezcla los datos"),
                      ("c", "Hay que usar pie")],
                     "a", "label= en plot + ax.legend()."),
        ]),
        (3, "Practica: anotar lo importante", "Un número clave vale más que diez ticks.", [
            mc("u20-l3-e1", "annotate o text sobre la barra más alta sirve para…",
               [("a", "Decir el valor exacto del mensaje"),
                ("b", "Sustituir los datos"),
                ("c", "Ocultar outliers")],
               "a", "El ojo va al número. Que sea el correcto."),
            predict("u20-l3-e2", "Si ylim va de 95 a 100 con datos 96-99, ¿qué sensación da?",
                    "print('diferencias exageradas')", "diferencias exageradas",
                    "El recorte convierte un 3% en un abismo visual."),
            code("u20-l3-e3",
                 "`ymin, ymax = 0, 10`. Imprime `ymax - ymin` (el rango que mostrarías).",
                 "ymin, ymax = 0, 10\n",
                 ["ymax - ymin == 10"],
                 "ymin, ymax = 0, 10\nprint(ymax - ymin)",
                 "Saber el rango del eje es parte del diseño del gráfico.",
                 expected_stdout="10"),
            matching("u20-l3-e4", "Accesible.",
                     [{"id": "l1", "text": "Contraste"}, {"id": "l2", "text": "No solo color"}, {"id": "l3", "text": "Tamaño de fuente"}],
                     [{"id": "r1", "text": "Se lee en pantalla barata"},
                      {"id": "r2", "text": "Forma o trazo además del tinte"},
                      {"id": "r3", "text": "Se lee en un móvil"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Daltonismo: no pongas rojo/verde como único código."),
        ]),
        (4, "Demuestra: menos tinta, más verdad", "Quita lo que no informa.", [
            mc("u20-l4-e1", "3D en un gráfico de barras 2D suele…",
               [("a", "Dificultar comparar alturas"),
                ("b", "Añadir un eje de datos real"),
                ("c", "Ser requisito de Matplotlib")],
               "a", "Tinta de chartjunk. Deja 2D claro."),
            find_err("u20-l4-e2", "Doble eje Y con escalas distintas y sin aviso. ¿Riesgo?",
                     [("a", "Inventas una relación visual que los números no tienen"),
                      ("b", "Python crashea"),
                      ("c", "Siempre es más honesto")],
                     "a", "Si usas twin axes, dilo y alinea ceros si puedes."),
            matching("u20-l4-e3", "Cortar.",
                     [{"id": "l1", "text": "Fondo oscuro ruidoso"}, {"id": "l2", "text": "Marco grueso"},
                      {"id": "l3", "text": "Ticks de más"}],
                     [{"id": "r1", "text": "Compite con la línea"},
                      {"id": "r2", "text": "No añade dato"},
                      {"id": "r3", "text": "Satura; deja 4-6 bien puestos"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Cada elemento debe ganar su sitio."),
            code("u20-l4-e4",
                 "`ticks = [0, 5, 10, 15]`. Imprime `len(ticks)` (cuántos marcas pondrías).",
                 "ticks = [0, 5, 10, 15]\n",
                 ["len(ticks) == 4"],
                 "ticks = [0, 5, 10, 15]\nprint(len(ticks))",
                 "Cuatro ticks leíbles ganan a veinte ilegibles.",
                 expected_stdout="4"),
        ]),
    ]))
    out.update(three(h, "u21", [
        (2, "Afianza: gráficos que entienden tablas", "Seaborn: data=, x=, y=, hue=.", [
            mc("u21-l2-e1", "`hue` en Seaborn es…",
               [("a", "Color según una categoría, para comparar grupos"),
                ("b", "El brillo del fondo"),
                ("c", "Un tipo de histograma")],
               "a", "No es decoración: es un agrupador."),
            matching("u21-l2-e2", "Función.",
                     [{"id": "l1", "text": "histplot"}, {"id": "l2", "text": "boxplot"}, {"id": "l3", "text": "heatmap"}],
                     [{"id": "r1", "text": "Forma de una variable"},
                      {"id": "r2", "text": "Comparar grupos (mediana, bigotes)"},
                      {"id": "r3", "text": "Matriz de colores (corr)"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "boxplot enseña outliers sin listarlos todos."),
            fill("u21-l2-e3", "Pasa la tabla.", "sns.barplot(data=___, x='mes', y='ventas')", [{"accepted": ["df"]}],
                 "data=df. Sin tabla, Seaborn pierde la magia."),
            find_err("u21-l2-e4", "Usar Seaborn sin columnas con nombre. ¿Qué echas de menos?",
                     [("a", "Un DataFrame (o dict) con x e y nombrados"),
                      ("b", "Un modelo sklearn"),
                      ("c", "GPU")],
                     "a", "Con listas sueltas, Matplotlib basta."),
        ]),
        (3, "Practica: la gramática x/y/hue", "Nombra las columnas, no los índices.", [
            mc("u21-l3-e1", "x='especie', y='peso', hue='sexo' compara…",
               [("a", "Peso por especie, partido por sexo"),
                ("b", "Solo el sexo"),
                ("c", "Un mapa geográfico")],
               "a", "Tres variables en un gráfico: dos ejes y el color."),
            predict("u21-l3-e2", "¿Cuántas series pinta hue con 2 categorías?",
                    "print(2)", "2",
                    "Una línea/caja/color por nivel de hue."),
            code("u21-l3-e3",
                 "`cols = ['x', 'y', 'hue']`. Imprime `len(cols)` (mínimo mental de un sns relplot).",
                 "cols = ['x', 'y', 'hue']\n",
                 ["len(cols) == 3"],
                 "cols = ['x', 'y', 'hue']\nprint(len(cols))",
                 "No siempre usas hue, pero el vocabulario es ese trío.",
                 expected_stdout="3"),
            matching("u21-l3-e4", "Cuándo Seaborn brilla.",
                     [{"id": "l1", "text": "Tienes un df limpio"}, {"id": "l2", "text": "Quieres un heatmap de corr"},
                      {"id": "l3", "text": "Control milimétrico del artista"}],
                     [{"id": "r1", "text": "barplot/histplot en una línea"},
                      {"id": "r2", "text": "sns.heatmap(df.corr())"},
                      {"id": "r3", "text": "Matplotlib puro"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Seaborn pinta; ax de Matplotlib sigue ahí si lo necesitas."),
        ]),
        (4, "Demuestra: no dejes que hue mienta", "Demasiados colores = no se lee.", [
            mc("u21-l4-e1", "hue con 40 países en un scatter…",
               [("a", "Suele ser ilegible; agrupa o faceta"),
                ("b", "Es el caso ideal"),
                ("c", "Sustituye a x e y")],
               "a", "FacetGrid o top-N. El color aguanta ~3-6 grupos."),
            find_err("u21-l4-e2", "Heatmap de correlación sin que X esté numérica. ¿Qué falta?",
                     [("a", "Seleccionar columnas numéricas antes de corr"),
                      ("b", "Un pie chart"),
                      ("c", "hue=index")],
                     "a", "df.select_dtypes('number').corr()."),
            matching("u21-l4-e3", "Caja (boxplot).",
                     [{"id": "l1", "text": "Línea central"}, {"id": "l2", "text": "Caja"}, {"id": "l3", "text": "Puntos fuera"}],
                     [{"id": "r1", "text": "Mediana"},
                      {"id": "r2", "text": "Rango intercuartílico"},
                      {"id": "r3", "text": "Outliers candidatos"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "No son errores automáticos: son 'mira esto'."),
            code("u21-l4-e4",
                 "`grupos = 3`. Imprime grupos (máximo de hue que te permites en un gráfico de charla).",
                 "grupos = 3\n",
                 ["grupos == 3"],
                 "grupos = 3\nprint(grupos)",
                 "Una regla casera: 3 colores, 1 mensaje.",
                 expected_stdout="3"),
        ]),
    ]))
    out.update(three(h, "u22", [
        (2, "Afianza: una frase, un gráfico", "El título puede ser la conclusión.", [
            mc("u22-l2-e1", "Mejor título…",
               [("a", "El canal web duplica a tienda en Q3"),
                ("b", "Gráfico 1"),
                ("c", "Ventas")],
               "a", "El título es la afirmación. El gráfico la prueba."),
            matching("u22-l2-e2", "Hábito.",
                     [{"id": "l1", "text": "Ordenar barras"}, {"id": "l2", "text": "Anotar el número clave"},
                      {"id": "l3", "text": "Quitar 3D"}],
                     [{"id": "r1", "text": "Por valor, salvo orden natural"},
                      {"id": "r2", "text": "El ojo aterriza"},
                      {"id": "r3", "text": "Deja de distorsionar alturas"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Meses sí van en orden temporal. Países, por magnitud."),
            fill("u22-l2-e3", "Antes de plot, escribe la palabra que falta.",
                 "Antes de dibujar, escribe la ___.",
                 [{"accepted": ["frase", "afirmacion", "afirmación", "conclusion", "conclusión"]}],
                 "Si no hay frase, hay exploración, no storytelling."),
            find_err("u22-l2-e4", "Un dashboard con 16 mini-gráficos sin mensaje. ¿Qué falla?",
                     [("a", "Nadie sale con una frase; recorta a 1-3 vistas"),
                      ("b", "Faltan más gráficos"),
                      ("c", "Hay que usar 3D en todos")],
                     "a", "Storytelling es restar."),
        ]),
        (3, "Practica: el número que se lleva el jefe", "Elige UN KPI y defiéndelo.", [
            code("u22-l3-e1",
                 "`web, tienda = 80, 40`. `ratio = web / tienda`. Imprime int(ratio).",
                 "web, tienda = 80, 40\n",
                 ["abs(ratio - 2) < 1e-9"],
                 "web, tienda = 80, 40\nratio = web / tienda\nprint(int(ratio))",
                 "El gráfico dirá 'web duplica'. El número 2 es el titular.",
                 expected_stdout="2"),
            mc("u22-l3-e2", "Eje que no empieza en 0 en barras…",
               [("a", "Puede exagerar diferencias; úsalo solo con aviso"),
                ("b", "Es siempre más honesto"),
                ("c", "Es obligatorio en Seaborn")],
               "a", "En líneas de temperatura, un eje recortado puede ser válido."),
            matching("u22-l3-e3", "Audiencia.",
                     [{"id": "l1", "text": "Científica"}, {"id": "l2", "text": "Ejecutiva"}, {"id": "l3", "text": "Pública general"}],
                     [{"id": "r1", "text": "Incertidumbre, n, método"},
                      {"id": "r2", "text": "Una decisión y el número que la mueve"},
                      {"id": "r3", "text": "Analogía y eje legible"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "El mismo dato, tres gráficos distintos."),
            predict("u22-l3-e4", "¿Cuántos mensajes debe cargar un gráfico de slide?",
                    "print(1)", "1",
                    "Uno. El resto va al apéndice."),
        ]),
        (4, "Demuestra: no escondas el denominador", "Porcentajes sin base mienten.", [
            mc("u22-l4-e1", "'+50%' con n=2. ¿Qué falta en el titular?",
               [("a", "El tamaño de muestra / valores absolutos"),
                ("b", "Un pie chart"),
                ("c", "Más decimales")],
               "a", "De 2 a 3 es +50% y no es un fenómeno."),
            find_err("u22-l4-e2", "Comparar ciudades con totales sin per cápita. ¿Sesgo?",
                     [("a", "Gana la más poblada aunque sea menos intensa"),
                      ("b", "Python ordena mal"),
                      ("c", "No se pueden comparar números")],
                     "a", "Decide: ¿total o tasa? Dilo."),
            code("u22-l4-e3",
                 "`casos, hab = 10, 200`. `tasa = casos / hab`. Imprime tasa.",
                 "casos, hab = 10, 200\n",
                 ["abs(tasa - 0.05) < 1e-9"],
                 "casos, hab = 10, 200\ntasa = casos / hab\nprint(tasa)",
                 "10 de 200 es 5%. El absoluto 10 no se entiende solo.",
                 expected_stdout="0.05"),
            matching("u22-l4-e4", "Checklist final.",
                     [{"id": "l1", "text": "Frase"}, {"id": "l2", "text": "Fuente / n"}, {"id": "l3", "text": "Unidades"}],
                     [{"id": "r1", "text": "Qué debe recordar la audiencia"},
                      {"id": "r2", "text": "De dónde salió y cuántos hay"},
                      {"id": "r3", "text": "USD, %, ºC…"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Si falta uno de los tres, el gráfico no viaja bien."),
        ]),
    ]))
    out.update(_project(h, "p2", "dashboard estático", "n_vistas",
                        "vistas = ['serie', 'barras', 'kpi']\nn_vistas = len(vistas)\nprint(n_vistas)",
                        ["n_vistas == 3"], "3",
                        "Tres vistas, un mensaje cada una. Un dashboard no es un álbum de 20 plots."))
    return out


def _project(h, uid, tema, var, solution, tests, stdout, extra_why):
    mc, fill, predict, code, matching, find_err = (
        h["mc"], h["fill"], h["predict"], h["code"], h["matching"], h["find_err"],
    )
    return three(h, uid, [
        (2, f"Afianza: qué pide este proyecto", f"El núcleo de {tema} es un cálculo que puedes defender.", [
            mc(f"{uid}-l2-e1", f"En el proyecto de {tema}, ganas si…",
               [("a", "El número cuadra, el código corre y explicas la decisión"),
                ("b", "El notebook tiene 40 celdas vacías"),
                ("c", "Usas la librería más nueva sin resultado")],
               "a", extra_why),
            matching(f"{uid}-l2-e2", "Orden de ataque.",
                     [{"id": "l1", "text": "Entrada"}, {"id": "l2", "text": "Cálculo"}, {"id": "l3", "text": "Comunicar"}],
                     [{"id": "r1", "text": "Lista, CSV o array conocido"},
                      {"id": "r2", "text": "Una métrica con nombre"},
                      {"id": "r3", "text": "Un print o un párrafo"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Si no puedes nombrar la métrica, aún no empezaste."),
            fill(f"{uid}-l2-e3", "El resultado vive en una variable, no solo en la pantalla.",
                 f"print({var})", [{"accepted": [var]}],
                 "Así un test puede leerla. print es para ti."),
            find_err(f"{uid}-l2-e4", "Entregar solo un pantallazo sin el cálculo. ¿Por qué no vale?",
                     [("a", "No es reproducible: nadie puede repetir el número"),
                      ("b", "Los proyectos no usan números"),
                      ("c", "Hace falta GPU")],
                     "a", "Reproducible > bonito."),
        ]),
        (3, f"Practica: el cálculo de {tema}", "Haz el núcleo con datos minúsculos.", [
            code(f"{uid}-l3-e1", f"Completa el núcleo del proyecto ({tema}).",
                 "", tests, solution, extra_why, expected_stdout=stdout),
            mc(f"{uid}-l3-e2", "Si la lista/array viniera vacío, ¿qué harías antes de la media?",
               [("a", "Comprobar len y decidir error claro o None"),
                ("b", "Dividir igual"),
                ("c", "Inventar 42")],
               "a", "Los bordes son parte del proyecto."),
            predict(f"{uid}-l3-e3", "¿Por qué un ejemplo de 3 filas ayuda?",
                    "print('puedes calcularlo a mano y contrastar')",
                    "puedes calcularlo a mano y contrastar",
                    "Si no cuadra a mano, el código está mal."),
            matching(f"{uid}-l3-e4", "Defensa del número.",
                     [{"id": "l1", "text": "Unidades"}, {"id": "l2", "text": "Filtros"}, {"id": "l3", "text": "Redondeo"}],
                     [{"id": "r1", "text": "¿ºC, USD, cuentas?"},
                      {"id": "r2", "text": "Qué filas metiste y cuáles no"},
                      {"id": "r3", "text": "Calcula fino, presenta corto"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "El número sin contexto no es un insight."),
        ]),
        (4, f"Demuestra: portafolio de {tema}", "Lo que escribirías debajo del gráfico.", [
            mc(f"{uid}-l4-e1", "Un párrafo de conclusiones debe incluir…",
               [("a", "Qué viste, qué no viste, y qué harías después"),
                ("b", "Solo 'éxito'"),
                ("c", "El código pegado otra vez")],
               "a", "Límites y siguiente paso = madurez."),
            find_err(f"{uid}-l4-e2", "Copiar un notebook ajeno sin cambiar datos ni tesis. ¿El fallo?",
                     [("a", "No hay decisión tuya ni resultado original"),
                      ("b", "GitHub lo impide"),
                      ("c", "Python no corre código copiado")],
                     "a", "El proyecto evalúa tu criterio."),
            matching(f"{uid}-l4-e3", "Checklist de envío.",
                     [{"id": "l1", "text": "Cómo correrlo"}, {"id": "l2", "text": "Dónde está el número"},
                      {"id": "l3", "text": "Qué NO afirma"}],
                     [{"id": "r1", "text": "Dependencias y comando"},
                      {"id": "r2", "text": "Variable o celda marcada"},
                      {"id": "r3", "text": "Límites del toy set"}],
                     {"l1": "r1", "l2": "r2", "l3": "r3"},
                     "Un README de 8 líneas gana a 8 mil de prosa."),
            predict(f"{uid}-l4-e4", "¿Cuántas frases mínimas tiene un hallazgo honesto?",
                    "print(2)", "2",
                    "Qué pasó + con qué datos. Opcional: y ahora qué."),
        ]),
    ])
